import {targetGradeBand} from '@/lib/stem/gradeBands';
import type {ResearchSession} from './session';
import type {ResearchConfig} from './config';
import type {STEMTask} from '@/types';
import {fingerprint} from './traceability';
export interface StartContext {interfaceLanguage:'zh-CN'|'en';taskLanguage:'zh-CN'|'en';provider:string;model:string}
export interface ConfigSnapshot extends StartContext {targetGradeBand?:import("@/types").TargetGradeBand;condition:string;taskDefinitionId:string;taskRevision:number;promptVersion:string;fadingEnabled:boolean;escalationEnabled:boolean;AIChallengeEnabled:boolean;manualSupportChange:boolean;messageTextStorage:boolean;timestamp:string;maxAICallsPerSession:number;maxTokensPerSession:number;idleThresholdMs:number}
export interface ActivityClock {lastTick:number;lastActivity:number;activeDurationMs:number;visible:boolean;idle:boolean}
export function initialSnapshot(task:STEMTask,c:ResearchConfig,now:number,context:StartContext):ConfigSnapshot {return {...context,targetGradeBand:targetGradeBand(task),condition:c.condition,taskDefinitionId:task.id,taskRevision:task.taskRevision??1,promptVersion:'young-learner-v3',fadingEnabled:c.enableFading,escalationEnabled:c.enableEscalation,AIChallengeEnabled:c.enableAIChallenge,manualSupportChange:c.allowManualSupportChange,messageTextStorage:c.storeMessageText,timestamp:new Date(now).toISOString(),maxAICallsPerSession:c.maxAICallsPerSession,maxTokensPerSession:c.maxTokensPerSession,idleThresholdMs:c.idleThresholdMs};}
export function taskTrace(task:STEMTask){return {taskDefinitionId:task.id,taskRevision:task.taskRevision??1,taskSnapshotHash:fingerprint(task)};}
export function tick(clock:ActivityClock,now:number,threshold:number):ActivityClock {now=Math.max(now,clock.lastTick);const end=Math.min(now,clock.lastActivity+threshold);return {...clock,lastTick:now,activeDurationMs:clock.activeDurationMs+(clock.visible&&!clock.idle?Math.max(0,end-clock.lastTick):0),idle:clock.idle||now>=clock.lastActivity+threshold};}
export function durations(s:ResearchSession,now:number){const end=Date.parse(s.completedAt??s.endedAt??'')||now;return {elapsedDurationMs:Math.max(0,end-Date.parse(s.startedAt)),activeDurationMs:Math.min(Math.max(0,end-Date.parse(s.startedAt)),tick(s.activity,end,s.config.idleThresholdMs).activeDurationMs)};}
export function usageSummary(s:ResearchSession){const events=s.events.filter(e=>e.eventType==='AI_RESPONSE'||e.eventType==='AI_ERROR');return {aiCalls:s.usage.aiCalls,inputTokens:s.usage.inputTokens,outputTokens:s.usage.outputTokens,totalTokens:s.usage.totalTokens,demoResponses:events.filter(e=>e.coach?.provider==='demo').length,fallbacks:events.filter(e=>e.coach?.fallbackReason).length,errors:events.filter(e=>e.eventType==='AI_ERROR').length};}
