import { describe, it, expect } from 'vitest';
import { demoTasks } from '@/data/tasks';
import { conditionConfig, initialLevel, type Condition } from '@/lib/research/config';
import { decidePedagogicalAction } from '@/lib/pedagogy/decisionEngine';
import { adaptiveDemo } from '@/lib/pedagogy/responses';
import { parseChatRequest } from '@/lib/stem/validation';
import type { ChatRequest } from '@/types';
const base:ChatRequest={task:demoTasks[0],stage:'understand',level:1,message:'',history:[],artifacts:{},completed:[],mode:'demo'};
const turn=(texts:string[],extra:Partial<ChatRequest>={}):ChatRequest=>({...base,...extra,history:texts.slice(0,-1).map(text=>({role:'student',text})),message:texts.at(-1)??''});
const stuck=['我不知道从哪里开始。','我还是不知道。'];
const productive=['3 metres 是成功标准，因为它规定了最低要求。','Wind power 是动力来源，材料限制会影响设计。'];
describe('adaptive UX validation A–F',()=>{
 it('A: two uncertainties offer Level 2 but do not switch automatically',()=>{const r=turn(stuck);expect(decidePedagogicalAction(r).recommendation).toBe(2);expect(r.level).toBe(1);expect(adaptiveDemo(r).text).toContain('小车');const reply=adaptiveDemo({...r,level:2,intent:'support-change',previousLevel:1});expect(reply.text).toContain('拆开');expect(reply.text).toContain('3 米');expect(reply.text).toContain('？');});
 it('B: Level 3 explicitly refers to task information and gives choices',()=>{const text=adaptiveDemo(turn(stuck,{level:3})).text;expect(text).toContain('3 米');expect(text).toContain('1. ');expect((text.match(/？/g)??[])).toHaveLength(1);});
 it('C: exact short bilingual sequence makes fading reachable only after two productive turns',()=>{expect(decidePedagogicalAction(turn([...stuck,productive[0]],{level:2})).recommendation).toBeUndefined();const r=turn([...stuck,...productive],{level:2});expect(decidePedagogicalAction(r).recommendation).toBe(1);expect(adaptiveDemo({...r,level:1,previousLevel:2,intent:'support-change'}).text).toContain('小提示');});
 it('requires recent reasoning/evidence rather than old evidence',()=>{const r=turn([productive[0],'I do not know.','The task has a goal to achieve.','The task has constraints to follow.'],{level:2});expect(decidePedagogicalAction(r).recommendation).toBeUndefined();});
 it.each(['LOW_SUPPORT','ADAPTIVE_SUPPORT','HIGH_SUPPORT'] as Condition[])('D/E: %s has a distinct starting policy',condition=>{const r=turn(stuck,{research:conditionConfig(condition),level:initialLevel(condition)});const d=decidePedagogicalAction(r),text=adaptiveDemo(r).text;if(condition==='LOW_SUPPORT'){expect(d.recommendation).toBeUndefined();expect(text).not.toContain('A.');}if(condition==='ADAPTIVE_SUPPORT')expect(d.recommendation).toBe(2);if(condition==='HIGH_SUPPORT'){expect(text).toContain('1. ');expect(d.recommendation).toBeUndefined();}});
 it('F: English and Chinese support changes follow the learner language',()=>{for(const [messages,needle] of [[stuck,'小'],[["I don't know.","I still don't know."],'small']] as const){expect(adaptiveDemo(turn([...messages],{level:3,previousLevel:2,intent:'support-change'})).text).toContain(needle);}expect(adaptiveDemo(turn(['I can explain the success criterion because it specifies performance.'],{level:2,previousLevel:3,intent:'support-change'})).text).toContain('less guidance');});
 it('two explicit requests can escalate, one cannot',()=>{expect(decidePedagogicalAction(turn(['Please help me.'])).recommendation).toBeUndefined();expect(decidePedagogicalAction(turn(['Please help me.','I need a stronger hint.'])).recommendation).toBe(2);});
 it('minimum readiness overrides mandatory scaffolding while preserving selected Level 3',()=>{const r=turn(productive,{level:3});expect(adaptiveDemo(r).text).not.toContain('这一步已经够用了');expect(r.level).toBe(3);});
 it('validates support-transition metadata and preserves the request level',()=>{expect(parseChatRequest({...base,message:'Adjust guidance.',intent:'support-change',level:2,previousLevel:3}).previousLevel).toBe(3);expect(()=>parseChatRequest({...base,message:'Adjust guidance.',intent:'support-change',previousLevel:9})).toThrow();expect(()=>parseChatRequest({...base,message:'Hi',previousLevel:2})).toThrow();});
});
