import { describe,it,expect } from 'vitest';
import { decidePedagogicalAction,applySupportChoice,artifactProgress,readiness } from '@/lib/pedagogy/decisionEngine';
import { detectSignals,languageOf } from '@/lib/pedagogy/signals';
import { adaptiveDemo } from '@/lib/pedagogy/responses';
import { demoTasks } from '@/data/tasks';
import type {ChatRequest,StageId} from '@/types';
const base:ChatRequest={task:demoTasks[0],stage:'understand',level:1,message:'',history:[],artifacts:{},completed:[]};
const scenario=(texts:string[],extra:Partial<ChatRequest>={}):ChatRequest=>({...base,...extra,history:texts.slice(0,-1).map(text=>({role:'student',text})),message:texts.at(-1)??''});
const progress=['The success criterion is to travel at least 3 metres because we need a measurable goal.','We must use the provided materials because this is a constraint.','We should measure the distance because this evidence will show whether the goal is met.'];
describe('adaptive scaffolding behavior',()=>{
 it('A: one uncertainty does not escalate, repeated uncertainty recommends without forcing',()=>{expect(decidePedagogicalAction(scenario(["I don’t know."])).recommendation).toBeUndefined();const d=decidePedagogicalAction(scenario(["I don't know where to start.","I’m not sure."]));expect(d.recommendation).toBe(2);expect(d.state.currentSupportLevel).toBe(1);expect(adaptiveDemo(scenario(["I don't know where to start.","I’m not sure."])).text).toContain('first sentence');});
 it('B: independent reasoning supports fading',()=>{expect(decidePedagogicalAction(scenario(progress,{level:2})).recommendation).toBe(1)});
 it('C/D: rejection preserves level; acceptance lowers one level',()=>{expect(applySupportChoice(3,2,false)).toBe(3);expect(applySupportChoice(3,2,true)).toBe(2)});
 it('E: contextual evidence enables challenge in Test',()=>{const req=scenario(['I observed different results in repeated trials.','I measured three results because repeated observations reveal variation.','The results always support this method.'],{stage:'test'});expect(decidePedagogicalAction(req).challengeEligible).toBe(true);const reply=adaptiveDemo({...req,intent:'evaluate-claim'});expect(reply.text).toMatch(/evidence/);expect(reply.text).not.toMatch(/correct answer|is true|is false/)});
 it('F: confusion suppresses challenges, even with completed records',()=>{expect(decidePedagogicalAction(scenario(["I don't know.","I still don't understand."],{artifacts:{understand:{'Problem statement':'We need to explain our measurable goal.'}}})).challengeEligible).toBe(false)});
 it.each([demoTasks[0],demoTasks[1],demoTasks[4]])('G: task isolation for $title',task=>{const r=adaptiveDemo(scenario(['I do not know.'],{task,level:3}));expect(r.text).toContain(task.successCriteria![0]);for(const other of demoTasks.filter(t=>t.id!==task.id))expect(r.text).not.toContain(other.title)});
 it('H: Chinese and English response/suggestions follow active language',()=>{const zh=adaptiveDemo(scenario(['我还是不知道怎么开始。']));expect(zh.text).toMatch(/[\u3400-\u9fff]/);expect(zh.suggestions.every(s=>/[\u3400-\u9fff]/.test(s))).toBe(true);const en=adaptiveDemo(scenario(["I don’t know."]));expect(en.text).not.toMatch(/[\u3400-\u9fff]/);expect(languageOf('I measured 3 cm')).toBe('en')});
 it('I: meaningful records contribute, blank and nonsense do not',()=>{expect(artifactProgress(base.task,'understand',{understand:{'Problem statement':'  ','Constraints':'asdfghjklasdfghjkl'}})).toHaveLength(0);const records={understand:{'Success criteria':'Travel at least three metres with the provided resources.'}};expect(artifactProgress(base.task,'understand',records)).toHaveLength(1);expect(readiness(base.task,'understand',records)).not.toContain('Success criteria');expect(decidePedagogicalAction({...base,artifacts:records}).state.progressScore).toBeGreaterThan(0)});
 it('J: stage-specific signals distinguish goals from Test evidence',()=>{const text='The goal is to meet the stated success criterion.';expect(detectSignals(text,'understand').productive).toBe(true);expect(detectSignals(text,'test').productive).toBe(false)});
 it('recognizes disagreement positively and repetition does not accumulate progress',()=>{expect(detectSignals('I disagree','test').critical).toBe(true);expect(detectSignals('We need evidence','test').evidence).toBe(true);expect(detectSignals(progress[0],'understand',[progress[0]]).productive).toBe(false)});
 it('support becomes more concrete, without revealing a complete solution',()=>{const req=scenario(["I don't know.","I still don't know."]);const a=adaptiveDemo(req).text,b=adaptiveDemo({...req,level:2}).text,c=adaptiveDemo({...req,level:3}).text;expect(a).not.toBe(b);expect(b).toContain('sentence');expect(c).toContain('3 metres');expect(c).toContain('A.');});
 it.each(['imagine','plan','build','test','improve','reflect'] as StageId[])('keeps stage-specific scaffolds for %s',stage=>{expect(adaptiveDemo({...base,stage,level:3,message:'I need more help.'}).text).not.toBe(adaptiveDemo({...base,stage:'understand',level:3,message:'I need more help.'}).text)});
});

it('support choice messages do not count as new learner evidence',()=>{const r=scenario(progress,{level:2});const original=decidePedagogicalAction(r).state;const changed=decidePedagogicalAction({...r,history:[...r.history,{role:'student',text:r.message}],intent:'support-change',message:'Please continue at my chosen support level.'}).state;expect(changed.consecutiveProductiveResponses).toBe(original.consecutiveProductiveResponses);expect(changed.progressScore).toBe(original.progressScore)});
it('claim quotation does not override the language of the student response',()=>{expect(adaptiveDemo({...base,intent:'evaluate-claim',message:'Regarding this unverified claim: “One result means the method always works under all conditions.”\n\n我不同意，需要更多证据。'}).suggestions[0]).toMatch(/我/)});
it('progress shifts the next focus from goal to conditions to evidence',()=>{expect(adaptiveDemo(scenario([progress[0]],{level:2})).text).toContain('other condition');expect(adaptiveDemo(scenario(progress.slice(0,2),{level:2})).text).toContain('evidence');expect(adaptiveDemo(scenario(progress,{level:2})).text).toContain('on your own')});
