import {windTurns,dialogue,rubricRequest} from './progression-fixtures';
import {shouldPromptReady,readyPromptCopy} from '@/lib/stem/readyPrompt';
import {finishSession} from '@/lib/research/session';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
vi.mock('server-only',()=>({}));
import {assessLocalReadiness,evidenceForStage,requestReadiness,semanticReadiness,readinessCriteria,readinessInstruction,READINESS_POLICY_VERSION} from '@/lib/stem/readiness';
import {deepseekProvider,pedagogicallyValid} from '@/lib/ai/deepseekProvider';
import {demoProvider} from '@/lib/ai/demoProvider';
import {respond} from '@/lib/ai';
import {newProject,parseProject} from '@/lib/projects/storage';
import {stageCheckpoints} from '@/lib/stem/stageCheckpoints';
import {startSession,recordEvent,enterStage,completeStage} from '@/lib/research/session';
import {conditionConfig} from '@/lib/research/config';
import {exportJSON,exportCSV} from '@/lib/research/export';
import {demoTasks} from '@/data/tasks';
import type {ChatRequest,StageId} from '@/types';
const task=demoTasks[0];
const base:ChatRequest={stage:'understand',level:2,task,message:'我们要让这个小车跑起来。',history:[],artifacts:{},completed:[]};
const examples:[StageId,string,boolean][]=[['understand','我们要让这个小车跑起来。',true],['understand','让它至少跑三米。',true],['imagine','我想把帆做大一点。',true],['plan','我先把大帆装上去试试。',true],['build','我准备装大帆。',false],['build','我刚刚已经把大帆装上去了。',true],['test','我觉得它会跑3米。',false],['test','刚才跑了2.1米。',true],['test','2.3米',true],['test','它倒了。',true],['test','It went farther this time.',true],['test','I will test it tomorrow.',false],['improve','我想把轮子调直一点。',true],['reflect','我发现测试以后再修改会更好。',true],['imagine','不知道。',false],['imagine','好的。',false],['imagine','我喜欢吃香蕉。',false]];
describe('single contributions are partial evidence, identical at every support level',()=>{
 it.each(examples)('%s: %s → %s',(stage,message,ready)=>{for(const level of [1,2,3] as const){const r={...base,stage,message,level};void ready;expect(requestReadiness(r).ready).toBe(false);expect(demoProvider(r).readiness?.ready).toBe(false);}});
 it('only learner evidence counts; adoption must contain an idea',()=>{const r={...base,stage:'imagine' as const,history:[{role:'assistant' as const,text:'可以试试改变帆的大小。'}],message:'好的。'};expect(requestReadiness(r).ready).toBe(false);expect(requestReadiness({...r,message:'那我想先把帆做大一点试试。'}).ready).toBe(false);});
 it('synthetic support changes and AI claims never supply evidence',()=>{expect(requestReadiness({...base,intent:'support-change',message:'我要做风力小车'}).ready).toBe(false);expect(requestReadiness({...base,intent:'challenge',message:'我要做风力小车'}).ready).toBe(false);});
 it.each(['好的','嗯','不知道','随便','下一步','ok','yes','idk'])('acknowledgement %s never supplies semantic evidence',message=>expect(semanticReadiness({ready:true,criterion:'BASIC_TASK_GOAL'},{...base,message}).ready).toBe(false));
 it.each([['build','I will build it tomorrow.'],['test','我觉得它会跑3米。']] as const)('semantic output cannot bypass temporal distinction in %s',(stage,message)=>expect(semanticReadiness({ready:true,criterion:readinessCriteria[stage]},{...base,stage,message}).ready).toBe(false));
 it('one record never replaces five successful dialogue rounds',()=>{const answers=['做一个风力小车','把帆变大','我先装上大帆试试','我已经试了一次','刚才跑了2.1米','把轮子调直','我发现轮子很重要'];for(const [i,stage] of (Object.keys(readinessCriteria) as StageId[]).entries()){const key=stageCheckpoints(task,stage)[0].field;expect(assessLocalReadiness(task,stage,{[stage]:{[key]:answers[i]}}).ready).toBe(false);}});
 it('Build plans and Test predictions stay insufficient even in a record field',()=>{expect(evidenceForStage(task,'build','我准备装大帆。',true)).toBe(false);expect(evidenceForStage(task,'test','我觉得它会跑3米。',true)).toBe(false);});
 it('a directly unsafe intention is not ready',()=>{expect(requestReadiness({...base,task:demoTasks[2],stage:'plan',message:'我要喝过滤后的水。'}).ready).toBe(false);});
 it('permissive records are not a correctness or mastery score',()=>expect(assessLocalReadiness(task,'understand',{'understand':{'Problem statement':'我想造能飞的风力小车'}}).ready).toBe(false));
});
describe('durable readiness and research privacy',()=>{
 it('restoring completion twice is idempotent, while explicit reopening still logs',()=>{const s=completeStage(startSession(task,conditionConfig()),'understand');expect(completeStage(s,'understand')).toBe(s);const reopened=completeStage(s,'understand',false);expect(reopened.events.at(-1)?.eventType).toBe('STAGE_REOPENED');expect(completeStage(reopened,'understand',false)).toBe(reopened);});
 it('migrates old projects without modifying notes, messages, completion or support v2',()=>{const p=newProject(task);p.records={imagine:{'Ideas or hypotheses':'把帆变大'}};p.conversations={understand:[{id:'1',role:'assistant',text:'What is the goal?'},{id:'2',role:'student',text:'我们要让这个小车跑起来。'}]};p.completed=['understand'];p.active='imagine';p.notebook='Keep my notes';const {readiness:_r,readinessPolicyVersion:_v,...old}=p;void _r;void _v;const next=parseProject(old);expect(next.readiness.imagine).toMatchObject({ready:false,meaningfulRounds:0});expect(next).toMatchObject({records:p.records,conversations:p.conversations,completed:p.completed,notebook:p.notebook,level:2,supportPolicyVersion:'v2',readinessPolicyVersion:READINESS_POLICY_VERSION});expect(parseProject(next)).toEqual(next);});
 it('readiness latches through reload and subsequent confusion; it never advances stage',()=>{const p=newProject(task);p.active='imagine';p.conversations.imagine=dialogue(windTurns.imagine);p.readiness.imagine=assessLocalReadiness(task,'imagine',{},p.conversations.imagine,'AI_SEMANTIC');const restored=parseProject(JSON.parse(JSON.stringify(p)));expect(restored.readiness.imagine?.ready).toBe(true);expect(restored.active).toBe('imagine');expect(restored.completed).toEqual([]);});
 it('STAGE_READY emits once per task/stage and has no raw text with capture OFF',()=>{let s=startSession(task,conditionConfig());const data={ready:true,reasonCategory:'TASK_STAGE_RUBRIC',meaningfulRounds:5,requiredRounds:5,criteriaSatisfiedCount:3,criteriaRequiredCount:3,readinessPolicyVersion:READINESS_POLICY_VERSION,taskRevision:2,readinessSource:'AI_SEMANTIC' as const,systemAction:'SEMANTIC_MINIMUM_EVIDENCE',messageText:'Private learner idea'};s=enterStage(s,'imagine');s=recordEvent(s,'STAGE_READY',data,Date.now(),'imagine');s=recordEvent(s,'STAGE_READY',data,Date.now(),'imagine');expect(s.events.filter(e=>e.eventType==='STAGE_READY')).toHaveLength(1);for(const out of [exportJSON(s),exportCSV(s)]){expect(out).toContain('TASK_STAGE_RUBRIC');expect(out).toContain('AI_SEMANTIC');expect(out).not.toContain('Private learner idea');}expect(s.completedStages).toEqual([]);s=enterStage(completeStage(s,'imagine'),'plan');expect(s.events.slice(-2).map(e=>e.eventType)).toEqual(['STAGE_COMPLETED','STAGE_ENTERED']);});
 it('new policy does not relabel v4 research archives',()=>{const s=startSession(task,conditionConfig());delete s.readinessPolicyVersion;delete s.configSnapshot.readinessPolicyVersion;s.promptVersion='young-learner-v4';s.configSnapshot.promptVersion='young-learner-v4';const out=JSON.parse(exportJSON(s));expect(out.promptVersion).toBe('young-learner-v4');expect(out.manifest.readinessPolicyVersion).toBe('checkpoint-v1');});
});
describe('one structured provider request, independent pedagogy checks',()=>{
 const reply=demoProvider(base).text;
 beforeEach(()=>{vi.stubEnv('DEEPSEEK_API_KEY','not-a-real-test-key');vi.stubGlobal('fetch',vi.fn());});
 afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
 function output(content:string){vi.mocked(fetch).mockResolvedValue(Response.json({model:'deepseek-flash',choices:[{finish_reason:'stop',message:{content}}]}));}
 it('returns coaching and readiness from the same JSON request',async()=>{output(JSON.stringify({reply,readiness:{ready:true,criterion:'BASIC_TASK_GOAL'}}));const r=await deepseekProvider(base);expect(r).toMatchObject({text:reply,readiness:{ready:false,meaningfulRounds:1,source:'AI_SEMANTIC'},metadata:{promptVersion:'young-learner-v6',supportPolicyVersion:'v2',readinessPolicyVersion:'task-rubric-v1'}});expect(fetch).toHaveBeenCalledTimes(1);expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).response_format).toEqual({type:'json_object'});expect(pedagogicallyValid(r.text,base)).toBe(true);expect(readinessInstruction('imagine')).toContain('task-rubric-v1');});
 it.each([undefined,{ready:true,criterion:'ACTUAL_RESULT'},{ready:'yes'},null])('bad readiness %j preserves valid reply without regeneration',async readiness=>{output(JSON.stringify({reply,readiness}));const r=await deepseekProvider(base);expect(r.text).toBe(reply);expect(r.readiness).toMatchObject({ready:false,source:'AI_SEMANTIC'});expect(fetch).toHaveBeenCalledTimes(1);});
 it('salvages valid reply string from a malformed metadata tail',async()=>{output('{"reply":'+JSON.stringify(reply)+',"readiness": INVALID}');expect((await deepseekProvider(base)).text).toBe(reply);expect(fetch).toHaveBeenCalledTimes(1);});
 it('plain valid coaching is retained if JSON parsing fails',async()=>{output(reply);expect((await deepseekProvider(base)).text).toBe(reply);expect(fetch).toHaveBeenCalledTimes(1);});
 it('structured output never weakens text safety',async()=>{output(JSON.stringify({reply:'1. Build the body\n2. Add wheels',readiness:{ready:true,criterion:'BASIC_TASK_GOAL'}}));await expect(deepseekProvider(base)).rejects.toMatchObject({code:'pedagogy'});expect(fetch).toHaveBeenCalledTimes(1);});
 it('NO_AI uses records and makes zero provider requests',async()=>{expect(assessLocalReadiness(task,'understand',{'understand':{'Problem statement':'让小车跑远一点'}}).ready).toBe(false);await expect(respond({...base,research:conditionConfig('NO_AI')})).rejects.toMatchObject({status:403});expect(fetch).not.toHaveBeenCalled();});
});

describe('required READY transition, including restored projects',()=>{
 const ready=requestReadiness(rubricRequest('imagine'));
 it('opens only on false to true in the active unfinished stage',()=>{expect(shouldPromptReady('imagine','imagine',[],undefined,ready)).toBe(true);expect(shouldPromptReady('imagine','understand',[],undefined,ready)).toBe(false);expect(shouldPromptReady('imagine','imagine',[],undefined,{...ready,ready:false})).toBe(false);});
 it('ADVANCE records decision before completion and canonical entry',()=>{let s=enterStage(startSession(task,conditionConfig()),'imagine');s=recordEvent(s,'STAGE_READY_DECISION',{studentAction:'ADVANCE'});s=enterStage(completeStage(s,'imagine'),'plan');expect(s.events.slice(-3).map(e=>e.eventType)).toEqual(['STAGE_READY_DECISION','STAGE_COMPLETED','STAGE_ENTERED']);expect(s.completedStages).toContain('imagine');expect(s.currentStage).toBe('plan');});
 it('STAY never completes or enters another stage',()=>{const s=recordEvent(enterStage(startSession(task,conditionConfig()),'imagine'),'STAGE_READY_DECISION',{studentAction:'STAY'});expect(s.completedStages).toEqual([]);expect(s.currentStage).toBe('imagine');});
 it('prior acknowledgement cannot suppress the required transition',()=>expect(shouldPromptReady('imagine','imagine',[],{...ready,promptSeen:true},ready)).toBe(true));
 it('refresh restores the required transition without an AI request',()=>{const p=newProject(task);p.active='imagine';p.conversations.imagine=dialogue(windTurns.imagine);p.readiness.imagine={...ready,promptSeen:true};const next=parseProject(JSON.parse(JSON.stringify(p)));expect(next.readiness.imagine).toEqual(p.readiness.imagine);expect(shouldPromptReady('imagine',next.active,next.completed,next.readiness.imagine,ready)).toBe(true);expect(next.readiness.imagine?.ready).toBe(true);});
 it('completed revisits do not prompt, but unfinished legacy READY projects do',()=>{expect(shouldPromptReady('imagine','imagine',['imagine'],undefined,ready)).toBe(false);expect(shouldPromptReady('imagine','imagine',[],ready,ready)).toBe(true);});
 it('Reflect finishes without an eighth stage, with final copy in both languages',()=>{expect(readyPromptCopy(true,true).advance).toBe('完成项目');expect(readyPromptCopy(true,false).advance).toBe('Finish Project');let s=startSession(task,conditionConfig());for(const stage of Object.keys(readinessCriteria) as StageId[])s=completeStage(enterStage(s,stage),stage);s=finishSession(s);expect(s.completedStages).toHaveLength(7);expect(s.currentStage).toBe('reflect');expect(s.completedAt).toBeDefined();});
 it.each(['Escape','backdrop','close'])('%s dismissal has STAY semantics and no raw text',()=>{const s=recordEvent(startSession(task,{...conditionConfig(),storeMessageText:true}),'STAGE_READY_DECISION',{studentAction:'STAY',messageText:'Never store this',reasonCategory:'Never store this'});expect(s.events.at(-1)).toMatchObject({eventType:'STAGE_READY_DECISION',studentAction:'STAY'});expect(s.events.at(-1)).not.toHaveProperty('messageText');expect(s.events.at(-1)).not.toHaveProperty('reasonCategory');expect(s.completedStages).toEqual([]);});
});
