import { describe,it,expect,vi } from 'vitest';
vi.mock('server-only',()=>({}));
import { conditionConfig,initialLevel,parseResearchConfig,researchMode } from '@/lib/research/config';
import { assignTask,taskFromQuery } from '@/lib/research/assignment';
import { startSession,recordEvent,changeTask,changeSupport,enterStage,completeStage,finishSession,reviseArtifact,setTextStorage,endSession } from '@/lib/research/session';
import { exportJSON,exportCSV } from '@/lib/research/export';
import { decidePedagogicalAction } from '@/lib/pedagogy/decisionEngine';
import { adaptiveDemo } from '@/lib/pedagogy/responses';
import { handleChat } from '@/lib/stem/handler';
import { demoTasks } from '@/data/tasks';
import type { ChatRequest } from '@/types';
const uncertain:ChatRequest={task:demoTasks[0],stage:'understand',level:1,message:"I still don't know.",history:[{role:'student',text:"I don't know."}],artifacts:{},completed:[],mode:'demo'};
const fresh=()=>startSession(demoTasks[0],conditionConfig(),1000);
describe('research conditions',()=>{
 it('A: low support does not proactively escalate, but honors an explicit level choice',()=>{const r={...uncertain,research:conditionConfig('LOW_SUPPORT')};expect(decidePedagogicalAction(r).recommendation).toBeUndefined();expect(adaptiveDemo({...r,level:2}).text).toContain('Look for');});
 it('B: adaptive escalation and fading remain active',()=>{expect(decidePedagogicalAction({...uncertain,research:conditionConfig()}).recommendation).toBe(2);const r={...uncertain,level:2 as const,research:conditionConfig(),history:[{role:'student' as const,text:'The goal is to travel 3 metres because success must be measurable.'},{role:'student' as const,text:'The constraint is provided materials because resources are limited.'}],message:'I will measure distance because it gives evidence of success.'};expect(decidePedagogicalAction(r).recommendation).toBe(1);});
 it('C: high support starts with a partial structure on the first uncertain turn',()=>{const research=conditionConfig('HIGH_SUPPORT');const r={...uncertain,history:[],level:initialLevel(research.condition),research};expect(adaptiveDemo(r).text).toContain('A. a resource');expect(decidePedagogicalAction(r).action).toBe('PROVIDE_STRUCTURED_SUPPORT');});
 it('D: no AI blocks generation at the server and still allows stage completion',async()=>{const research=conditionConfig('NO_AI');const generate=vi.fn();const res=await handleChat(new Request('http://localhost/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...uncertain,research})}),generate);expect(res.status).toBe(403);expect(generate).not.toHaveBeenCalled();expect(adaptiveDemo({...uncertain,research}).text).toBe('');expect(completeStage(startSession(demoTasks[0],research),'understand').completedStages).toEqual(['understand']);});
 it('validates conditions and respects disabled policies',()=>{expect(()=>parseResearchConfig({condition:'evil'})).toThrow();expect(()=>parseResearchConfig({condition:'CUSTOM',enableFading:'yes'})).toThrow();expect(decidePedagogicalAction({...uncertain,research:{...conditionConfig(),enableEscalation:false}}).recommendation).toBeUndefined();expect(researchMode('')).toBe(false);expect(researchMode('?research=1')).toBe(true);});
});
describe('session events and export',()=>{
 it('E: task change preserves the session but resets task-scoped state',()=>{let s=completeStage(fresh(),'understand',true,1500);s=reviseArtifact(s,'understand','Success criteria','Three metres',1600);const before=s.taskId;s=changeTask(s,demoTasks[4],2000);expect(s.sessionId).toBe(s.events[0].sessionId);expect(s.taskId).not.toBe(before);expect(s.completedStages).toEqual([]);expect(s.currentStage).toBe('understand');expect(s.artifactRevisions.filter(r=>r.taskId===s.taskId)).toEqual([]);expect(s.tasks[0].completedStages).toEqual(['understand']);expect(s.events.at(-1)?.eventType).toBe('TASK_CHANGED');});
 it('F: JSON includes ordered events, task metadata and completion time',()=>{let s=recordEvent(fresh(),'MESSAGE_SENT',{learnerSignal:['evidence']},1200);s=completeStage(s,'reflect',true,1400);s=finishSession(s,1500);const data=JSON.parse(exportJSON(s,1600));expect(data.events.map((e:{eventType:string})=>e.eventType)).toEqual(['SESSION_STARTED','MESSAGE_SENT','STAGE_COMPLETED','SESSION_COMPLETED']);expect(data.tasks[0].catalogTaskId).toBe(demoTasks[0].id);expect(data.completedAt).toBe(new Date(1500).toISOString());expect(data.sessionId).toMatch(/^[a-f0-9-]{36}$/);expect(data.stageTimings[0].durationMs).toBe(500);});
 it('G: text OFF omits messages, revisions and free-form task metadata',()=>{let s=startSession({...demoTasks[0],id:'private-id',title:'private title',description:'private description'},conditionConfig(),1000);s=recordEvent(s,'MESSAGE_SENT',{messageText:'private message'},1100);s=reviseArtifact(s,'understand','Constraints','private artifact',1200);for(const text of [exportJSON(s),exportCSV(s)])expect(text).not.toMatch(/private message|private artifact|private title|private description|private-id/);});
 it('H: ON captures only subsequent text, and OFF purges it from JSON and CSV',()=>{let s=recordEvent(fresh(),'MESSAGE_SENT',{messageText:'before opt-in'},1100);s=setTextStorage(s,true);s=recordEvent(s,'AI_RESPONSE',{messageText:'after opt-in'},1200);s=reviseArtifact(s,'test','Observations','recorded details',1300);expect(exportJSON(s)).not.toContain('before opt-in');expect(exportJSON(s)).toContain('after opt-in');s=setTextStorage(s,false);expect(exportJSON(s)).not.toContain('after opt-in');expect(exportCSV(s)).not.toContain('recorded details');});
 it('I: support history records each initiator and the initial level',()=>{let s=fresh();s=changeSupport(s,2,'STUDENT',1100);s=changeSupport(s,1,'SYSTEM_RECOMMENDATION',1200);expect(s.supportHistory.map(h=>h.initiator)).toEqual(['RESEARCH_CONDITION','STUDENT','SYSTEM_RECOMMENDATION']);expect(s.supportHistory[1]).toMatchObject({from:1,to:2});});
 it('J: stage transitions and backwards clock cannot create negative duration',()=>{let s=enterStage(fresh(),'test',2000);s=enterStage(s,'reflect',1500);expect(s.stageTimings[0].durationMs).toBe(1000);expect(s.stageTimings[1].durationMs).toBe(0);expect(JSON.parse(exportJSON(s,1000)).stageTimings.every((t:{durationMs:number})=>t.durationMs>=0)).toBe(true);});
 it('K: two edits create two artifact versions, text optional',()=>{let s=reviseArtifact(fresh(),'understand','Problem statement','First version',1100);s=reviseArtifact(s,'understand','Problem statement','Second version',1200);expect(s.artifactRevisions.map(r=>r.version)).toEqual([1,2]);expect(s.artifactRevisions[1]).toMatchObject({characterCount:14});expect(s.artifactRevisions[1].text).toBeUndefined();});
 it('L: challenge choice, follow-up and self-reported revision link to the same challenge',()=>{let s=recordEvent(fresh(),'AI_CHALLENGE_STARTED',{challengeId:'example',aiChallengeTriggered:true});s=recordEvent(s,'AI_CHALLENGE_RESPONSE',{challengeId:'example',learnerChoice:'DISAGREE'});s=recordEvent(s,'AI_CHALLENGE_FOLLOW_UP',{challengeId:'example',followUpAction:'TEST',laterRevision:'UNCERTAIN'});expect(s.events.at(-1)).toMatchObject({challengeId:'example',followUpAction:'TEST',laterRevision:'UNCERTAIN'});expect(exportJSON(s)).not.toContain('correctness');});
 it('CSV quotes Unicode, newlines and neutralizes spreadsheet formula text',()=>{let s=setTextStorage(fresh(),true);s=recordEvent(s,'MESSAGE_SENT',{messageText:'=HYPERLINK("bad")\n中文'});expect(exportCSV(s)).toContain('"\'=HYPERLINK(""bad"")\n中文"');});
 it('reset is not falsely recorded as successful completion',()=>{const s=endSession(fresh(),'RESET',2000);expect(s.completedAt).toBeUndefined();expect(s.tasks[0].completedAt).toBeUndefined();expect(s.endReason).toBe('RESET');expect(s.events.at(-1)?.eventType).toBe('SESSION_ENDED');});
 it('background response retains request stage and support level',()=>{const s=changeSupport(enterStage(fresh(),'test'),3,'STUDENT');expect(recordEvent(s,'AI_RESPONSE',{},2000,'understand',1).events.at(-1)).toMatchObject({stage:'understand',supportLevel:1});});
});
describe('task assignment',()=>{
 it('seeded assignments are reproducible and honor eligibility',()=>{expect(assignTask(demoTasks,'all','pilot01')).toEqual(assignTask([...demoTasks].reverse(),'all','pilot01'));expect(assignTask(demoTasks,'scientific-inquiry','pilot01').type).toBe('scientific-inquiry');expect(()=>assignTask(demoTasks,'optimization','pilot01')).toThrow('No eligible');});
 it.each([demoTasks[0],demoTasks[1],demoTasks[4],demoTasks[3]])('supports $title without cross-task coaching',task=>{const s=startSession(task,conditionConfig('HIGH_SUPPORT'));expect(s.tasks[0].catalogTaskId).toBe(task.id);const text=adaptiveDemo({...uncertain,task,level:3}).text;expect(text).toContain(task.successCriteria![0]);for(const other of demoTasks.filter(t=>t.id!==task.id))expect(text).not.toContain(other.title);});
 it('query assignment only accepts known task IDs',()=>{expect(taskFromQuery('?task=plants')?.id).toBe('plants');expect(()=>taskFromQuery('?task=unrecognized')).toThrow();expect(taskFromQuery('?research=1')).toBeUndefined();});
});
