import {windTurns,dialogue} from './progression-fixtures';
import {assessLocalReadiness} from '@/lib/stem/readiness';
import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {drizzle as pgliteDrizzle} from 'drizzle-orm/pglite';
import {migrate as migrateLite} from 'drizzle-orm/pglite/migrator';
import {Pool} from 'pg';
import {drizzle as pgDrizzle} from 'drizzle-orm/node-postgres';
import {migrate as migratePG} from 'drizzle-orm/node-postgres/migrator';
vi.mock('server-only',()=>({}));
import type {DB} from '@/lib/server/db';
import {Accounts,type Account} from '@/lib/server/accounts';
import {Projects} from '@/lib/server/projects';
import {ResearchStore,cleanResearch} from '@/lib/server/research';
import {hashPIN,verifyPIN,cookie,securityHash} from '@/lib/server/security';
import {platformConfig} from '@/lib/server/config';
import {attestReadiness,attestRound} from '@/lib/server/readinessReceipt';
import {guardedCoach} from '@/lib/server/coachAccess';
import {platformAPI} from '@/lib/server/api';
import {demoTasks} from '@/data/tasks';
import {stageIds} from '@/lib/stem/stages';
import {stageCheckpoints} from '@/lib/stem/stageCheckpoints';
import {conditionConfig} from '@/lib/research/config';
import {startSession,recordEvent} from '@/lib/research/session';
import {boundedHistory} from '@/lib/stem/context';
let db:DB,lite:PGlite|undefined,pool:Pool|undefined,admin:Account,a:Account,b:Account,accounts:Accounts,projects:Projects;
function fillStage(p:Awaited<ReturnType<Projects['get']>>,stage:typeof stageIds[number]){
 const turns=dialogue(windTurns[stage],stage);
 for(let index=1;index<turns.length;index+=2)turns[index].dialogue!.receipt=attestRound(p.id,p.task,stage,turns[index-1],turns[index],'chat');
 p.conversations[stage]=turns;
 p.readiness[stage]=attestReadiness(p.id,stage,assessLocalReadiness(p.task,stage,p.records,turns,'AI_SEMANTIC'));
}
const request=(path:string,method='GET',body?:unknown,token?:string,origin='http://localhost')=>new Request('http://localhost/api/platform/'+path,{method,headers:{host:'localhost',origin,'Content-Type':'application/json',...(token?{cookie:'stempath_session='+token}:{})},body:body?JSON.stringify(body):undefined});
beforeAll(async()=>{
 if(process.env.TEST_DATABASE_URL){const url=new URL(process.env.TEST_DATABASE_URL);if(url.pathname!=='/stempath_test')throw Error('Database tests require a dedicated stempath_test database');pool=new Pool({connectionString:url.toString()});await migratePG(pgDrizzle(pool),{migrationsFolder:'drizzle'});const source=pool;db={query:async(sql,params)=>(await source.query(sql,params)).rows,transaction:async fn=>{const c=await source.connect();try{await c.query('BEGIN');const tx:DB={query:async(s,p)=>(await c.query(s,p)).rows,transaction:f=>f(tx)};const r=await fn(tx);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};}
 else{lite=new PGlite();await migrateLite(pgliteDrizzle(lite),{migrationsFolder:'drizzle'});const source=lite;db={query:async(sql,params)=>(await source.query(sql,params)).rows as never,transaction:fn=>source.transaction(async tx=>{const connection:DB={query:async(s,p)=>(await tx.query(s,p)).rows as never,transaction:f=>f(connection)};return fn(connection);})};}
},30000);
beforeEach(async()=>{vi.stubEnv('SESSION_SECRET','isolated-test-secret-not-a-production-value');vi.stubEnv('PERSISTENCE_MODE','postgres');vi.stubEnv('AUTH_MODE','participant');vi.stubEnv('STUDENT_TASK_MODE','OPEN');await db.query('TRUNCATE users,task_definitions,login_limits CASCADE');accounts=new Accounts(db);projects=new Projects(db);admin=(await accounts.create('ADMIN01','ADMIN','87465193')).account;a=(await accounts.create('P001','STUDENT','482196')).account;b=(await accounts.create('P002','STUDENT','596317')).account;},15000);
afterEach(()=>vi.unstubAllEnvs());afterAll(async()=>{await lite?.close();await pool?.end();});
describe('participant accounts and sessions',()=>{
 it('uses separate internal UUIDs and case-normalized unique codes',async()=>{expect(a.id).not.toBe(a.participantCode);expect(a.id).not.toBe(b.id);await expect(accounts.create('p001')).rejects.toMatchObject({status:409});});
 it('hashes PINs with independent salts and constant-time verification',async()=>{const h=await hashPIN('482196'),h2=await hashPIN('482196');expect(h).not.toContain('482196');expect(h).not.toBe(h2);expect(await verifyPIN('482196',h)).toBe(true);expect(await verifyPIN('000000',h)).toBe(false);});
 it('rejects invalid PINs and unknown accounts generically',async()=>{await expect(accounts.login('P001','000000','deviceA')).rejects.toMatchObject({status:401});await expect(accounts.login('NOUSER','000000','deviceA')).rejects.toMatchObject({status:401});});
 it('logs in with an opaque token, storing only its hash',async()=>{const login=await accounts.login('P001','482196','deviceA');expect(await accounts.authenticate(request('session','GET',undefined,login.token))).toEqual(a);const [r]=await db.query('SELECT * FROM auth_sessions');expect(r.token_hash).toBe(securityHash(login.token));expect(JSON.stringify(r)).not.toContain(login.token);});
 it('expires an eight-hour session',async()=>{let now=Date.now();const clock=new Accounts(db,()=>now),login=await clock.login('P001','482196','deviceA');now+=8*3600_000+1;await expect(clock.authenticate(request('session','GET',undefined,login.token))).rejects.toMatchObject({status:401});});
 it('logout revokes the database session',async()=>{const login=await accounts.login('P001','482196','deviceA');await accounts.logout(request('logout','POST',{},login.token));await expect(accounts.authenticate(request('session','GET',undefined,login.token))).rejects.toMatchObject({status:401});});
 it('uses HttpOnly, SameSite and production Secure cookies',()=>{vi.stubEnv('NODE_ENV','production');expect(cookie('abc',3600)).toContain('HttpOnly; SameSite=Lax');expect(cookie('abc',3600)).toContain('; Secure');expect(cookie('',0)).toContain('Max-Age=0');});
 it('limits guesses per account, with temporary recovery',async()=>{let now=Date.now();const clock=new Accounts(db,()=>now);for(let i=0;i<5;i++)await expect(clock.login('P001','000000','deviceA')).rejects.toMatchObject({status:401});await expect(clock.login('P001','482196','deviceA')).rejects.toMatchObject({status:429});now+=15*60_000+1;expect((await clock.login('P001','482196','deviceA')).account.id).toBe(a.id);});
 it('limits distributed account guessing by ingress IP without storing raw IPs',async()=>{for(let i=0;i<20;i++)await accounts.limit('UNKNOWN'+i,'192.0.2.1');await expect(accounts.limit('ANOTHER','192.0.2.1')).rejects.toMatchObject({status:429});expect(JSON.stringify(await db.query('SELECT * FROM login_limits'))).not.toContain('192.0.2.1');});
 it('reset replaces the hash, revokes sessions and clears the account cooldown',async()=>{const login=await accounts.login('P001','482196','deviceA');const reset=await accounts.reset(admin,a.id);await expect(accounts.authenticate(request('session','GET',undefined,login.token))).rejects.toMatchObject({status:401});await expect(accounts.login('P001','482196','deviceA')).rejects.toMatchObject({status:401});expect((await accounts.login('P001',reset.displayPIN,'deviceA')).account.id).toBe(a.id);});
 it('disabled users cannot log in or use old sessions',async()=>{const login=await accounts.login('P001','482196','deviceA');await accounts.disable(admin,a.id);await expect(accounts.login('P001','482196','deviceA')).rejects.toMatchObject({status:401});await expect(accounts.authenticate(request('session','GET',undefined,login.token))).rejects.toMatchObject({status:401});});
 it('batch creation gives independent random credentials and rolls back collisions',async()=>{const created=await accounts.batch('T',3);expect(created).toHaveLength(3);expect(new Set(created.map(c=>c.account.id)).size).toBe(3);expect(created.every(c=>/^\d{6}$/.test(c.displayPIN))).toBe(true);await expect(accounts.batch('T',3)).rejects.toMatchObject({status:409});expect((await accounts.list()).filter(c=>c.participantCode.startsWith('T'))).toHaveLength(3);});
 it('students cannot reset, disable or delete accounts',async()=>{await expect(accounts.reset(a,b.id)).rejects.toMatchObject({status:403});await expect(accounts.disable(a,b.id)).rejects.toMatchObject({status:403});await expect(accounts.remove(a,b.id,'DELETE P002')).rejects.toMatchObject({status:403});});
});
describe('normalized project persistence and isolation',()=>{
 it('stores an immutable task revision and normalized stage rows',async()=>{const p=await projects.create(a,demoTasks[1],'OPEN');expect(p.serverVersion).toBe(1);expect((await db.query('SELECT * FROM project_stage_state WHERE project_id=$1',[p.id]))).toHaveLength(7);await expect(projects.create(a,{...demoTasks[1],description:'Changed without a revision'},'OPEN')).rejects.toMatchObject({status:409});});
 it('P002 cannot read, overwrite, delete or get messages from P001',async()=>{const p=await projects.create(a,demoTasks[1],'OPEN');p.conversations.understand=[{id:'learner1',role:'student',text:'Private P001 text'}];await projects.save(a,p.id,p,1);expect((await projects.get(a,p.id)).conversations.understand?.[0].suggestions).toBeUndefined();expect(await projects.list(b)).toEqual([]);await expect(projects.get(b,p.id)).rejects.toMatchObject({status:404});await expect(projects.save(b,p.id,p,2)).rejects.toMatchObject({status:404});await expect(projects.remove(b,p.id,'DELETE PROJECT')).rejects.toMatchObject({status:404});});
 it('reconstructs full conversations, two completed stages, checkpoint, notebook and support on a fresh device',async()=>{let p=await projects.create(a,demoTasks[0],'OPEN');for(const stage of stageIds.slice(0,2)){fillStage(p,stage);p.records[stage]={'Checkpoint':'Learner-produced checkpoint answer'};}p.completed=['understand','imagine'];p.active='plan';p.level=2;p.notebook='Keep this note';p.challenges.imagine={claim:'A claim to check',choice:'需要证据',revision:'UNCERTAIN',mode:'demo'};p=await projects.save(a,p.id,p,p.serverVersion);const deviceB=new Projects(db),restored=await deviceB.get(a,p.id);expect(restored.active).toBe('plan');expect(restored.completed).toEqual(expect.arrayContaining(['understand','imagine']));expect(restored.conversations).toEqual(p.conversations);expect(restored.records).toEqual(p.records);expect(restored.notebook).toBe('Keep this note');expect(restored.level).toBe(2);expect(restored.challenges.imagine?.choice).toBe('需要证据');});
 it('rejects stale versions without losing the newer conversation',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');const stale=structuredClone(p);p.notebook='Newer device note';await projects.save(a,p.id,p,1);stale.notebook='Stale note';await expect(projects.save(a,p.id,stale,1)).rejects.toMatchObject({status:409});expect((await projects.get(a,p.id)).notebook).toBe('Newer device note');});
 it('preserves the full failed student turn without generating or retrying AI',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.conversations.understand=Array.from({length:50},(_,i)=>({id:'message-'+i,role:i%2?'assistant':'student',text:'Message '+i}));p.conversations.understand.push({id:'failed-student',role:'student',text:'Network failed after I sent this'});await projects.save(a,p.id,p,1);const restored=await projects.get(a,p.id);expect(restored.conversations.understand).toHaveLength(51);expect(restored.conversations.understand?.at(-1)?.role).toBe('student');expect(boundedHistory(restored.conversations.understand!)).toHaveLength(8);});
 it('rejects completion without the local deterministic core records',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.completed=['understand'];p.active='imagine';await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});expect((await projects.get(a,p.id)).completed).toEqual([]);});
 it('allows a READY checkpoint without marking mastery or automatically advancing',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.records.understand={'Problem statement':'让小车前进','Success criteria':'至少3米'};await projects.save(a,p.id,p,1);const [s]=await db.query('SELECT status FROM project_stage_state WHERE project_id=$1 AND stage=\'understand\'',[p.id]);expect(s.status).toBe('IN_PROGRESS');expect((await projects.get(a,p.id)).active).toBe('understand');});
 it('ASSIGNED requires the assigned exact revision and locks the condition',async()=>{await projects.assign(admin,a.id,demoTasks[1],conditionConfig('HIGH_SUPPORT'));await expect(projects.create(a,demoTasks[0],'ASSIGNED')).rejects.toMatchObject({status:403});const p=await projects.create(a,demoTasks[1],'ASSIGNED');expect(p.level).toBe(3);expect(p.researchConfig.condition).toBe('HIGH_SUPPORT');expect(await projects.assigned(b)).toEqual([]);});
 it('rejects forged assigned task content',async()=>{await projects.assign(admin,a.id,demoTasks[0],conditionConfig('ADAPTIVE_SUPPORT'));await expect(projects.create(a,{...demoTasks[0],description:'Other task'},'ASSIGNED')).rejects.toMatchObject({status:400});});
 it('NO_AI assignments reject assistant conversations and AI Challenge state',async()=>{await projects.assign(admin,a.id,demoTasks[0],conditionConfig('NO_AI'));const p=await projects.create(a,demoTasks[0],'ASSIGNED');p.conversations.understand=[{id:'a',role:'assistant',text:'An AI response'}];await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});});
});
describe('task-rubric server persistence',()=>{
 it('one record cannot bypass dialogue and rubric via Finish',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.records.understand={'Problem statement':'让小车跑起来'};p.completed=['understand'];p.active='imagine';await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});});
 it('signed completed rounds restore across devices and cannot be counted twice',async()=>{let p=await projects.create(a,demoTasks[0],'OPEN');fillStage(p,'understand');p.completed=['understand'];p.active='imagine';p=await projects.save(a,p.id,p,1);const other=await new Projects(db).get(a,p.id);expect(other.readiness.understand).toMatchObject({ready:true,meaningfulRounds:5,requiredRounds:5,policyVersion:'task-rubric-v1'});expect(other.conversations.understand?.[1].dialogue?.receipt).toBeDefined();const again=await projects.save(a,p.id,other,other.serverVersion);expect(again.readiness.understand?.meaningfulRounds).toBe(5);});
 it('rejects a forged successful coach round even with plausible content',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');fillStage(p,'understand');p.conversations.understand![1].dialogue!.receipt='f'.repeat(64);await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});expect((await projects.get(a,p.id)).readiness.understand?.meaningfulRounds).toBe(0);});
 it('signed model criteria cannot compensate for fewer than five successful rounds',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');fillStage(p,'understand');p.conversations.understand=p.conversations.understand!.slice(0,8);p.completed=['understand'];p.active='imagine';await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});});
 it('migrates old READY once without paid calls, keeps completed stages and notes',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.records.imagine={'Ideas or hypotheses':'把帆变大'};p.notebook='Keep this';await projects.save(a,p.id,p,1);await db.query("UPDATE projects SET readiness_policy_version='gentle-v1' WHERE id=$1",[p.id]);await db.query("UPDATE project_stage_state SET status='COMPLETED' WHERE project_id=$1 AND stage='understand'",[p.id]);const next=await projects.get(a,p.id);expect(next).toMatchObject({readinessPolicyVersion:'task-rubric-v1',notebook:'Keep this',serverVersion:3,level:2,supportPolicyVersion:'v2'});expect(next.readiness.imagine?.ready).toBe(false);expect(next.completed).toEqual(['understand']);expect(await projects.get(a,p.id)).toEqual(next);});
 it('NO_AI never invents dialogue rounds; teacher override remains separate',async()=>{await projects.assign(admin,a.id,demoTasks[0],conditionConfig('NO_AI'));const p=await projects.create(a,demoTasks[0],'ASSIGNED');p.records.understand={'Success criteria':'至少3米'};p.completed=['understand'];p.active='imagine';await expect(projects.save(a,p.id,p,1)).rejects.toMatchObject({status:400});const teacher=await projects.create(admin,demoTasks[0],'OPEN');teacher.completed=['understand'];teacher.active='imagine';expect((await projects.save(admin,teacher.id,teacher,1)).completed).toEqual(['understand']);});
 it('server retains prompt acknowledgement without changing round count',async()=>{let p=await projects.create(a,demoTasks[0],'OPEN');fillStage(p,'understand');p.readiness.understand!.promptSeen=true;p=await projects.save(a,p.id,p,1);p.readiness.understand!.promptSeen=false;p=await projects.save(a,p.id,p,p.serverVersion);expect(p.readiness.understand).toMatchObject({ready:true,promptSeen:true,meaningfulRounds:5});});
});
describe('server support policy migration',()=>{
 it('creates new server projects at Level 2 and records v2',async()=>{
  const p=await projects.create(a,demoTasks[0],'OPEN');expect(p).toMatchObject({level:2,supportPolicyVersion:'v2',serverVersion:1});
  const [row]=await db.query('SELECT support_policy_version FROM projects WHERE id=$1',[p.id]);expect(row.support_policy_version).toBe('v2');
 });
 it.each([[1,1],[2,1],[3,2]] as const)('atomically maps server legacy Level %s to %s once',(async(old,next)=>{
  const p=await projects.create(a,demoTasks[0],'OPEN');p.notebook='Keep my notebook';await projects.save(a,p.id,p,1);
  await db.query("UPDATE projects SET support_level=$2,support_policy_version='v1' WHERE id=$1",[p.id,old]);
  const migrated=await projects.get(a,p.id);expect(migrated).toMatchObject({level:next,supportPolicyVersion:'v2',notebook:p.notebook,serverVersion:3});
  expect(await projects.get(a,p.id)).toEqual(migrated);
  await expect(projects.save(a,p.id,p,2)).rejects.toMatchObject({status:409});
 }));
});
describe('research linkage, privacy and deliberate deletion',()=>{
 it('links research to the authenticated user and owned project, excludes PIN/security and raw text when OFF',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN'),research=new ResearchStore(db);let s=startSession(p.task,p.researchConfig);s=recordEvent(s,'MESSAGE_SENT',{messageText:'Private learner phrase'});await research.save(a,p.id,{...s,participantCode:'FORGED',pinHash:'secret',authSession:'secret'},0);const [r]=await db.query('SELECT user_id,project_id FROM research_sessions');expect(r.user_id).toBe(a.id);expect(r.project_id).toBe(p.id);const output=await research.export(admin,a.id);expect(output).toContain('P001');for(const secret of ['Private learner phrase','FORGED','pinHash','authSession'])expect(output).not.toContain(secret);await expect(research.latest(b,p.id)).rejects.toMatchObject({status:404});await expect(research.save(b,p.id,s,0)).rejects.toMatchObject({status:404});});
 it('captures opted-in text only under the server assignment policy',async()=>{const config={...conditionConfig(),storeMessageText:true};await projects.assign(admin,a.id,demoTasks[0],config);const p=await projects.create(a,demoTasks[0],'ASSIGNED'),store=new ResearchStore(db);const s=recordEvent(startSession(p.task,config),'MESSAGE_SENT',{messageText:'Opted-in text'});await store.save(a,p.id,s,0);expect(await store.export(admin,a.id)).toContain('Opted-in text');});
 it('rejects student changes to the assignment research condition or capture policy',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');const s=startSession(p.task,{...conditionConfig('HIGH_SUPPORT'),storeMessageText:true});await expect(new ResearchStore(db).save(a,p.id,s,0)).rejects.toMatchObject({status:400});});
 it('version-checks research updates and excludes extra nested security metadata',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN'),store=new ResearchStore(db);const s=startSession(p.task,p.researchConfig);expect(cleanResearch({...s,configSnapshot:{...s.configSnapshot,pinHash:'secret'}}).configSnapshot).not.toHaveProperty('pinHash');await store.save(a,p.id,s,0);await expect(store.save(a,p.id,s,0)).rejects.toMatchObject({status:409});});
 it('deletion requires an exact deliberate confirmation and cascades all learner data',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.conversations.understand=[{id:'s',role:'student',text:'Learner text'}];p.records.understand={'Problem statement':'An answer'};await projects.save(a,p.id,p,1);await new ResearchStore(db).save(a,p.id,startSession(p.task,p.researchConfig),0);await accounts.login('P001','482196','deviceA');await expect(accounts.remove(admin,a.id,'P001')).rejects.toMatchObject({status:400});await accounts.remove(admin,a.id,'DELETE P001');for(const table of ['projects','messages','learning_records','project_stage_state','research_sessions','research_events','auth_sessions'])expect(await db.query('SELECT * FROM '+table)).toEqual([]);expect((await accounts.list()).some(u=>u.id===b.id)).toBe(true);});
 it('project removal also removes linked research records and leaves the account',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');await new ResearchStore(db).save(a,p.id,startSession(p.task,p.researchConfig),0);await projects.remove(a,p.id,'DELETE PROJECT');expect(await db.query('SELECT * FROM research_sessions')).toEqual([]);expect((await accounts.list()).some(u=>u.id===a.id)).toBe(true);});
});
describe('HTTP boundary and current LOCAL compatibility',()=>{
 it('refuses unauthenticated project and message access',async()=>{expect((await platformAPI(request('projects'),['projects'],db)).status).toBe(401);const p=await projects.create(a,demoTasks[0],'OPEN');expect((await platformAPI(request('projects/'+p.id),['projects',p.id],db)).status).toBe(401);});
 it('rejects cross-user HTTP project access and student admin requests',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN'),login=await accounts.login('P002','596317','deviceB');expect((await platformAPI(request('projects/'+p.id,'GET',undefined,login.token),['projects',p.id],db)).status).toBe(404);expect((await platformAPI(request('admin/accounts','GET',undefined,login.token),['admin','accounts'],db)).status).toBe(403);});
 it('requires same-origin on login and all mutations, even with a valid cookie',async()=>{expect((await platformAPI(request('login','POST',{participantCode:'P001',pin:'482196'},undefined,'http://attacker.invalid'),['login'],db)).status).toBe(403);const login=await accounts.login('P001','482196','deviceA');expect((await platformAPI(request('projects','POST',{task:demoTasks[0]},login.token,'http://attacker.invalid'),['projects'],db)).status).toBe(403);});
 it('returns only a safe account view on login, with cookie-based authentication',async()=>{const r=await platformAPI(request('login','POST',{participantCode:'P001',pin:'482196'}),['login'],db);expect(r.status).toBe(200);expect(r.headers.get('Set-Cookie')).toContain('HttpOnly');const json=await r.json();expect(Object.keys(json)).toEqual(['account']);expect(json.account).not.toHaveProperty('pinHash');expect(r.headers.get('Cache-Control')).toBe('no-store');});
 it('LOCAL defaults do not initialize a database and do not expose account endpoints',async()=>{vi.stubEnv('PERSISTENCE_MODE','local');vi.stubEnv('AUTH_MODE','disabled');vi.stubEnv('DATABASE_URL','');expect(platformConfig().persistence).toBe('local');expect((await platformAPI(request('config'),['config'])).status).toBe(200);expect((await platformAPI(request('projects'),['projects'])).status).toBe(404);});
 it('fails closed for incompatible persistence/auth combinations',()=>{vi.stubEnv('AUTH_MODE','disabled');expect(()=>platformConfig()).toThrow('enabled together');});
});

describe('authenticated coach boundary without paid calls',()=>{
 it('forwards a framework-wrapped request through the full Demo handler',async()=>{
  const {handleChat}=await import('@/lib/stem/handler');
  const p=await projects.create(a,demoTasks[1],'OPEN'),login=await accounts.login('P001','482196','deviceA');
  const incoming=request('chat','POST',{projectId:p.id,interfaceLanguage:'zh-CN',task:demoTasks[0],stage:'understand',level:1,message:'我需要提示',history:[],artifacts:{},completed:[],mode:'demo'},login.token);
  // Framework adapters need not retain the native Request object's private brand.
  const wrapped={url:incoming.url,method:incoming.method,headers:incoming.headers,body:incoming.body} as Request;
  const response=await guardedCoach(wrapped,handleChat,false,db);
  expect(response.status).toBe(200);expect(await response.json()).toMatchObject({mode:'demo',text:expect.any(String)});
 });
 const body=(id:string)=>({projectId:id,task:demoTasks[1],stage:'understand',level:1,message:'I need a hint',history:[],artifacts:{},completed:[],research:conditionConfig('HIGH_SUPPORT')});
 it('rejects unauthenticated chat before any provider or database project reads',async()=>{const handler=vi.fn();expect((await guardedCoach(request('chat','POST',body('00000000-0000-0000-0000-000000000000')),handler,false,db)).status).toBe(401);expect(handler).not.toHaveBeenCalled();});
 it('rejects cross-user chat history access',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN'),login=await accounts.login('P002','596317','deviceB'),handler=vi.fn();expect((await guardedCoach(request('chat','POST',body(p.id),login.token),handler,false,db)).status).toBe(404);expect(handler).not.toHaveBeenCalled();});
 it('injects the authoritative task and research policy, retaining bounded client context',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN'),login=await accounts.login('P001','482196','deviceA');const handler=vi.fn(async(r:Request)=>Response.json(await r.json()));const response=await guardedCoach(request('chat','POST',body(p.id),login.token),handler,false,db);expect(response.status).toBe(200);const result=await response.json();expect(result.task.id).toBe(p.task.id);expect(result.research.condition).toBe('ADAPTIVE_SUPPORT');});
 it('blocks NO_AI even if the client forges a different condition',async()=>{await projects.assign(admin,a.id,demoTasks[0],conditionConfig('NO_AI'));const p=await projects.create(a,demoTasks[0],'ASSIGNED'),login=await accounts.login('P001','482196','deviceA'),handler=vi.fn();expect((await guardedCoach(request('chat','POST',body(p.id),login.token),handler,false,db)).status).toBe(403);expect(handler).not.toHaveBeenCalled();});
 it('requires a researcher for task-check calls',async()=>{const login=await accounts.login('P001','482196','deviceA'),handler=vi.fn();expect((await guardedCoach(request('task-check','POST',{task:demoTasks[0]},login.token),handler,true,db)).status).toBe(403);expect(handler).not.toHaveBeenCalled();});
});

describe('saved completion ceremony state',()=>{
 it('POSTGRES saves the once flag atomically with all seven stages and survives a fresh device',async()=>{
  let p=await projects.create(a,demoTasks[0],'OPEN');
  const evidence=['让小车跑起来','我想把帆加大','先装上帆','我已经装好了帆','跑了2.3米','我想把轮子调直','我发现实际测试很重要'];
  for(const [i,stage] of stageIds.entries()){fillStage(p,stage);p.records[stage]={[stageCheckpoints(p.task,stage).filter(c=>c.core)[0].field]:evidence[i]};}
  p.completed=[...stageIds];p.active='reflect';p.completionCelebrationSeen=true;
  p=await projects.save(a,p.id,p,p.serverVersion);expect(p.completionCelebrationSeen).toBe(true);
  const fresh=await new Projects(db).get(a,p.id);expect(fresh.completed).toHaveLength(7);expect(fresh.completionCelebrationSeen).toBe(true);
  fresh.completionCelebrationSeen=false;expect((await projects.save(a,p.id,fresh,fresh.serverVersion)).completionCelebrationSeen).toBe(true);
  expect((await db.query('SELECT status FROM projects WHERE id=$1',[p.id]))[0].status).toBe('COMPLETED');
 });
 it('an incomplete project cannot save a false completion celebration',async()=>{const p=await projects.create(a,demoTasks[0],'OPEN');p.completionCelebrationSeen=true;expect((await projects.save(a,p.id,p,p.serverVersion)).completionCelebrationSeen).toBe(false);});
});
