import type {CriterionKind,ProgressionCriteria,StageCriterion,StageId,STEMTask} from '@/types';
export const rubricStages:StageId[]=['understand','imagine','plan','build','test','improve','reflect'];
export const criterionKinds:CriterionKind[]=['TASK_GOAL','SUCCESS_CRITERION','ONE_CONSTRAINT_OR_RESOURCE','AT_LEAST_TWO_IDEAS','CHOSEN_DIRECTION','SIMPLE_REASON','CHANGE_FACTOR','AT_LEAST_ONE_CONTROLLED_CONDITION','MEASUREMENT','SIMPLE_PROCEDURE','ACTUAL_BUILD_ACTION','SECOND_ACTUAL_ACTION_OR_DETAIL','BUILD_OBSERVATION_OR_PROBLEM','ACTUAL_TRIAL_1','ACTUAL_TRIAL_2','COMPARE_WITH_GOAL','IDENTIFY_REVISION','HOW_TO_REVISE','LINK_TO_TEST_EVIDENCE','ONE_TAKEAWAY','EVIDENCE_OR_EXPERIENCE_CONNECTION','ONE_CHANGE_IN_THINKING_OR_NEXT_TIME'];
const profiles=['wind-car','bridge','filtration','insulation','plants','engineering','inquiry'] as const;
const kinds:Record<StageId,CriterionKind[]>={understand:['TASK_GOAL','SUCCESS_CRITERION','ONE_CONSTRAINT_OR_RESOURCE'],imagine:['AT_LEAST_TWO_IDEAS','CHOSEN_DIRECTION','SIMPLE_REASON'],plan:['CHANGE_FACTOR','AT_LEAST_ONE_CONTROLLED_CONDITION','MEASUREMENT','SIMPLE_PROCEDURE'],build:['ACTUAL_BUILD_ACTION','SECOND_ACTUAL_ACTION_OR_DETAIL','BUILD_OBSERVATION_OR_PROBLEM'],test:['ACTUAL_TRIAL_1','ACTUAL_TRIAL_2','COMPARE_WITH_GOAL'],improve:['IDENTIFY_REVISION','HOW_TO_REVISE','LINK_TO_TEST_EVIDENCE'],reflect:['ONE_TAKEAWAY','EVIDENCE_OR_EXPERIENCE_CONNECTION','ONE_CHANGE_IN_THINKING_OR_NEXT_TIME']};
const labels:Record<CriterionKind,string>={TASK_GOAL:'Explain what this task asks you to make or investigate / 说出要制作或探究什么',SUCCESS_CRITERION:'Recognize the task’s success or evidence goal / 知道怎样算成功或需要什么证据',ONE_CONSTRAINT_OR_RESOURCE:'Identify one relevant constraint or resource / 说出一个条件或可用材料',AT_LEAST_TWO_IDEAS:'Consider two plausible ideas or predictions / 考虑两个办法或猜想',CHOSEN_DIRECTION:'Choose one direction to try first / 选择先试的方向',SIMPLE_REASON:'Give a simple reason for that choice / 说出选择的理由',CHANGE_FACTOR:'Identify what to change or compare / 说出要改变或比较什么',AT_LEAST_ONE_CONTROLLED_CONDITION:'Identify one condition to keep the same / 说出每次保持一样的条件',MEASUREMENT:'Identify what to observe or measure / 说出要观察或测量什么',SIMPLE_PROCEDURE:'Describe a basic sequence for the comparison / 说出简单的尝试顺序',ACTUAL_BUILD_ACTION:'Report an actual build or setup action / 说出实际做过的一步',SECOND_ACTUAL_ACTION_OR_DETAIL:'Report another implementation detail or how it was done / 补充另一项实际动作或怎样做的',BUILD_OBSERVATION_OR_PROBLEM:'Report a real observation or problem while working / 说出动手时看到的情况或问题',ACTUAL_TRIAL_1:'Report one actual observed or measured trial / 说出第一次真实观察或测试',ACTUAL_TRIAL_2:'Report a second actual observed or measured trial / 说出第二次真实观察或测试',COMPARE_WITH_GOAL:'Compare actual results with the task goal / 把真实结果与目标比较',IDENTIFY_REVISION:'Identify a concrete revision / 说出具体想改哪一点',HOW_TO_REVISE:'Explain how to make that revision / 说出准备怎样改',LINK_TO_TEST_EVIDENCE:'Connect that change with something seen in testing / 联系测试中看到的情况',ONE_TAKEAWAY:'Explain one thing learned / 说出一个学习发现',EVIDENCE_OR_EXPERIENCE_CONNECTION:'Connect learning to a real result or experience / 联系一次实际经历或结果',ONE_CHANGE_IN_THINKING_OR_NEXT_TIME:'Explain changed thinking or what to do differently next time / 说出想法变化或下次怎样做'};
const specifics:Record<string,Partial<Record<CriterionKind,string>>>={
 'wind-car':{TASK_GOAL:'Make/test a wind-powered car / 制作测试风力小车',SUCCESS_CRITERION:'Recognize at least 3 metres / 至少行驶3米',ONE_CONSTRAINT_OR_RESOURCE:'Provided materials or wind propulsion / 提供的材料或用风推动',MEASUREMENT:'Measure travel distance / 测量行驶距离',COMPARE_WITH_GOAL:'Compare the results with 3 metres / 与3米目标比较'},
 bridge:{TASK_GOAL:'Build a model bridge spanning a gap / 制作跨越间隙的模型桥',SUCCESS_CRITERION:'Recognize 20 cm span and 200 g load for 10 seconds / 20厘米跨度、承重200克10秒',ONE_CONSTRAINT_OR_RESOURCE:'Paper/tape or safe supervised load testing / 纸和胶带或安全承重测试',MEASUREMENT:'Observe supported load and stability over time / 观察承重、稳定与持续时间',ACTUAL_TRIAL_1:'Report a real bridge load test / 一次真实承重测试',ACTUAL_TRIAL_2:'Report a second real bridge load test / 第二次真实承重测试',COMPARE_WITH_GOAL:'Compare span/load stability with the stated goal / 与跨度承重目标比较'},
 filtration:{TASK_GOAL:'Reduce visible particles using a filter / 用过滤减少可见颗粒',SUCCESS_CRITERION:'Compare visible particles/clarity before and after, never drinking / 比较过滤前后颗粒与清澈度，不能饮用',ONE_CONSTRAINT_OR_RESOURCE:'Recognize no drinking and a filter resource / 知道不能饮用及一种过滤材料',MEASUREMENT:'Observe before/after particles or clarity / 观察前后颗粒或清澈度',ACTUAL_TRIAL_1:'Report a real before/after filtration trial / 一次真实过滤前后观察',ACTUAL_TRIAL_2:'Report a second filtration comparison / 第二次过滤比较',COMPARE_WITH_GOAL:'Compare visible clarity, without claiming drinkability / 比较清澈度，不声称可饮用'},
 insulation:{TASK_GOAL:'Investigate material effects on cooling / 探究材料对冷却的影响',SUCCESS_CRITERION:'Compare temperature change over a fixed time / 固定时间比较温度变化',AT_LEAST_ONE_CONTROLLED_CONDITION:'Keep starting temperature, water amount or time the same / 保持起始温度、水量或时间一致',MEASUREMENT:'Measure temperature with elapsed time / 测量温度及时间',ACTUAL_BUILD_ACTION:'Actually prepare the safe warm-water comparison / 实际准备安全温水比较',ACTUAL_TRIAL_1:'Report temperature observations over a fixed time / 固定时间真实温度观察',ACTUAL_TRIAL_2:'Report a second temperature comparison / 第二次温度比较',COMPARE_WITH_GOAL:'Compare cooling with the investigation goal / 对照减缓冷却的探究目标'},
 plants:{TASK_GOAL:'Investigate light exposure and seedling growth / 探究光照与幼苗生长',SUCCESS_CRITERION:'Repeated growth measurements over time / 随时间重复测量生长',AT_LEAST_ONE_CONTROLLED_CONDITION:'Keep water, soil or plant type the same / 保持水、土或品种一致',MEASUREMENT:'Measure growth and record time/light conditions / 测量生长并记录时间光照',ACTUAL_BUILD_ACTION:'Actually set up and care for the plant comparison / 实际准备并照顾比较中的植物',ACTUAL_TRIAL_1:'Report an actual growth observation / 一次真实生长观察',ACTUAL_TRIAL_2:'Report another time-point or comparison observation / 另一时间或条件的真实观察',COMPARE_WITH_GOAL:'Relate observed growth to the light question, including limitations / 联系光照问题与观察局限'}
};
export function defaultRubric(task:Pick<STEMTask,'id'|'title'|'description'|'type'>):ProgressionCriteria{
 const profile:ProgressionCriteria['profile']=profiles.includes(task.id as typeof profiles[number])?task.id as ProgressionCriteria['profile']:/inquiry|investigation|modelling/.test(task.type)?'inquiry':'engineering';
 const inquiry=profile==='inquiry'||profile==='plants'||profile==='insulation';
 const result={minimumMeaningfulTurnsPerStage:5,profile} as ProgressionCriteria;
 for(const stage of rubricStages)result[stage]=kinds[stage].filter(kind=>!(stage==='build'&&profile==='engineering'&&kind==='SECOND_ACTUAL_ACTION_OR_DETAIL')).map(kind=>({id:profile==='wind-car'&&kind==='COMPARE_WITH_GOAL'?'COMPARE_WITH_3M_GOAL':kind,kind,label:specifics[profile]?.[kind]??(inquiry&&kind==='AT_LEAST_TWO_IDEAS'?'Consider two possible explanations or predictions / 考虑两个解释或猜想':inquiry&&kind==='ACTUAL_BUILD_ACTION'?'Report actual preparation of the investigation / 说出实际准备探究的一步':labels[kind])}));
 return result;
}
export function parseRubric(value:unknown,fallback:ProgressionCriteria):ProgressionCriteria{
 if(value===undefined)return structuredClone(fallback);
 if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid progression criteria');
 const v=value as Record<string,unknown>;const min=v.minimumMeaningfulTurnsPerStage??5,profile=v.profile??fallback.profile;
 if(!Number.isSafeInteger(min)||(min as number)<5||(min as number)>20||!profiles.includes(profile as typeof profiles[number]))throw Error('Use 5–20 meaningful rounds per stage.');
 const result={minimumMeaningfulTurnsPerStage:min,profile} as ProgressionCriteria;
 for(const stage of rubricStages){const list=v[stage]??fallback[stage];if(!Array.isArray(list)||list.length<1||list.length>8)throw Error('Use 1–8 criteria per stage.');const ids=new Set<string>();result[stage]=list.map(item=>{if(!item||typeof item!=='object')throw Error('Invalid criterion');const c=item as StageCriterion;if(typeof c.id!=='string'||! /^[A-Z][A-Z0-9_]{1,79}$/.test(c.id)||ids.has(c.id)||!criterionKinds.includes(c.kind)||typeof c.label!=='string'||!c.label.trim()||c.label.length>300)throw Error('Invalid criterion');ids.add(c.id);return {id:c.id,kind:c.kind,label:c.label.trim()};});}
 return result;
}
export function taskRubric(task:STEMTask){return task.progressionCriteria??defaultRubric(task);}
export function criterionLabel(kind:CriterionKind,zh:boolean){const parts=labels[kind].split(' / ');return parts[zh?1:0]??labels[kind];}
