import { useEffect,useRef,useState } from 'react';
import { apiCoach } from '@/lib/coach';
import type { Language } from '@/lib/pedagogy/signals';
import type { Choice } from '@/lib/research/session';
import type { ChatRequest } from '@/types';
export function AIChallenge({request,onRespond,disabled,language='en',onTrigger,onChoice,onRevision}:{language?:Language;onTrigger?:(claim:string)=>void;onChoice?:(choice:Choice)=>void;onRevision?:(revision:'ACCEPTED_CLAIM'|'REJECTED_CLAIM'|'UNCERTAIN')=>void;disabled?:boolean;request:ChatRequest;onRespond:(message:string,claim:string)=>void}) {
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [claim,setClaim]=useState('');const [mode,setMode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [choice,setChoice]=useState('');
 async function generate(){setBusy(true);setError('');try{const res=await apiCoach.respond({...request,intent:'challenge',message:language==='zh'?'请提出一个可以检验的说法。':'Offer a testable claim for this task that I can critically evaluate.'});if(!alive.current)return;setClaim(res.text);setMode(res.mode);onTrigger?.(res.text)}catch{if(!alive.current)return;setError('Could not load the claim. Try again.')}finally{setBusy(false)}}
 return <details className="rail-section ai-challenge"><summary>AI Challenge</summary><p>A claim is something to question, not an answer to trust.</p>{!claim?<button className="primary-button" disabled={busy||disabled} onClick={generate}>{busy?'Preparing…':'Explore a claim'}</button>:<><small>{mode==='demo'?'Demo claim':'AI-generated claim'} · Not verified</small><p>{claim}</p><div className="claim-choices">{(language==='zh'?['同意','不同意','需要证据']:['Agree','Disagree','Need evidence']).map((label,index)=><button disabled={disabled} aria-pressed={choice===label} key={label} onClick={()=>{setChoice(label);onChoice?.((['AGREE','DISAGREE','NEED_EVIDENCE'] as const)[index]);onRespond(language==='zh'?`我的看法是：${label}。`:`My response is: ${label}.`,claim)}}>{label}</button>)}</div>{choice&&<><p>What could you observe or measure to decide? Explain your reasoning in the coach chat.</p><label>After checking, my view is…<select aria-label="Later view of the claim" defaultValue="" onChange={e=>onRevision?.(e.target.value as 'ACCEPTED_CLAIM'|'REJECTED_CLAIM'|'UNCERTAIN')}><option value="" disabled>Optional update</option><option value="ACCEPTED_CLAIM">I accept the claim</option><option value="REJECTED_CLAIM">I reject the claim</option><option value="UNCERTAIN">I am still uncertain</option></select></label></>}</>}{error&&<p role="alert">{error}</p>}</details>;
}
