import {useI18n} from '@/lib/i18n';
import { useEffect,useRef,useState } from 'react';
import { apiCoach } from '@/lib/coach';
import type { Language } from '@/lib/pedagogy/signals';
import type { Choice } from '@/lib/research/session';
import type { ChatRequest } from '@/types';
export function AIChallenge({request,onRespond,disabled,language='en',onTrigger,onChoice,onRevision}:{language?:Language;onTrigger?:(claim:string)=>void;onChoice?:(choice:Choice)=>void;onRevision?:(revision:'ACCEPTED_CLAIM'|'REJECTED_CLAIM'|'UNCERTAIN')=>void;disabled?:boolean;request:ChatRequest;onRespond:(message:string,claim:string)=>void}) {
 const {t}=useI18n();

 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [claim,setClaim]=useState('');const [mode,setMode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [choice,setChoice]=useState('');
 async function generate(){setBusy(true);setError('');try{const res=await apiCoach.respond({...request,intent:'challenge',message:language==='zh'?'请提出一个可以检验的说法。':'Offer a testable claim for this task that I can critically evaluate.'});if(!alive.current)return;setClaim(res.text);setMode(res.mode);onTrigger?.(res.text)}catch{if(!alive.current)return;setError(t('Could not load the claim. Try again.'))}finally{setBusy(false)}}
 return <details open className="rail-section ai-challenge"><summary>{t("AI Challenge")}</summary><p>{language==='zh'?t("AI 的这个说法还没有被验证。请用证据判断。"):t("This claim has not been verified. Use evidence to evaluate it.")}</p>{!claim?<button className="primary-button" disabled={busy||disabled} onClick={generate}>{busy?t("Preparing…"):t("Explore a claim")}</button>:<><small>{mode==='demo'?t("Demo claim"):t("AI-generated claim")}{t("· Not verified")}</small><p>{claim}</p><div className="claim-choices">{(language==='zh'?['同意','不同意','需要证据']:['Agree','Disagree','Need evidence']).map((label,index)=><button disabled={disabled} aria-pressed={choice===label} key={label} onClick={()=>{setChoice(label);onChoice?.((['AGREE','DISAGREE','NEED_EVIDENCE'] as const)[index]);onRespond(language==='zh'?`我的看法是：${label}。`:`My response is: ${label}.`,claim)}}>{label}</button>)}</div>{choice&&<><p>{language==='zh'?t("什么证据能帮助你判断？你可以观察或测量什么？在对话中说说你的理由。"):t("What evidence would help you decide? What could you observe or measure? Explain your reasoning in the coach chat.")}</p><label>{t("After checking, my view is…")}<select aria-label={t("Later view of the claim")} defaultValue="" onChange={e=>onRevision?.(e.target.value as 'ACCEPTED_CLAIM'|'REJECTED_CLAIM'|'UNCERTAIN')}><option value="" disabled>{t("Optional update")}</option><option value="ACCEPTED_CLAIM">{t("I accept the claim")}</option><option value="REJECTED_CLAIM">{t("I reject the claim")}</option><option value="UNCERTAIN">{t("I am still uncertain")}</option></select></label></>}</>}{error&&<p role="alert">{error}</p>}</details>;
}
