'use client';
import {reviseTask} from '@/lib/research/traceability';
import {AITaskCheck} from './AITaskCheck';
import {useState} from 'react';
import {useI18n} from '@/lib/i18n';
import {localizedTask,loadTask,taskTypes} from '@/lib/stem/tasks';
import {duplicateTask,exportTasks,importTasks,type Project} from '@/lib/projects/storage';
import type {STEMTask} from '@/types';
export type View='Home'|'Challenges'|'My Projects'|'Resources'|'Library'|'Create'|'Preview'|'Workspace';
export function ProjectHub({view,library,examples,projects,preview,editing,researchMode,onView,onPreview,onStart,onContinue,onSave,onEdit,onDelete,onRemove,onRestart,onImport}:{view:View;library:STEMTask[];examples:STEMTask[];projects:Project[];preview:STEMTask|null;editing:STEMTask|null;researchMode:boolean;onView:(v:View)=>void;onPreview:(t:STEMTask)=>void;onStart:(t:STEMTask)=>void;onContinue:(p:Project)=>void;onSave:(t:STEMTask)=>void;onEdit:(t:STEMTask)=>void;onDelete:(id:string)=>void;onRemove:(id:string)=>void;onRestart:(p:Project)=>void;onImport:(tasks:STEMTask[])=>void}){
 const {t,locale}=useI18n();const [filter,setFilter]=useState('');const [json,setJSON]=useState('');const [error,setError]=useState('');const [exported,setExported]=useState('');const [confirm,setConfirm]=useState<{label:string;run:()=>void}|null>(null);
 const shown=(task:STEMTask)=>localizedTask(task,locale);
 const cards=(tasks:STEMTask[],manage=false)=><div className="hub-grid">{tasks.filter(task=>!filter||task.type===filter).map(task=>{const d=shown(task);return <article className="hub-card" key={task.id}><span className="hub-tag">{t(task.type)}</span><h3>{d.title}</h3><p>{d.description}</p><small>{[task.lessonNumber&&`${t('Lesson')} ${task.lessonNumber}`,d.gradeLevel,d.subject,task.estimatedMinutes&&`${task.estimatedMinutes} ${t('minutes')}`].filter(Boolean).join(' · ')}</small><div className="hub-actions"><button className="primary-button" onClick={()=>onPreview(task)}>{t('Preview')}</button>{manage&&<><button onClick={()=>onEdit(task)}>{t('Edit')}</button><button onClick={()=>onSave(duplicateTask(task,t(' — Copy')))}>{t('Duplicate')}</button><button onClick={()=>setExported(exportTasks([task]))}>{t('Export JSON')}</button><button onClick={()=>setConfirm({label:'Delete task?',run:()=>onDelete(task.id)})}>{t('Delete')}</button><button onClick={()=>onStart(task)}>{t('Assign Task to Session')}</button></>}</div></article>})}</div>;
 const projectCards=(items:Project[])=><div className="hub-grid">{items.map(p=><article className="hub-card" key={p.id}><span className="hub-tag">{t(p.task.type)}</span><h3>{shown(p.task).title}</h3><p>{t(`stage.${p.active}`)} · {p.completed.length} / 7 {t('stages completed')}</p><small>{t('Last opened')}: {new Date(p.lastOpenedAt).toLocaleString(locale)}</small><div className="hub-actions"><button className="primary-button" onClick={()=>onContinue(p)}>{t('Continue Project')}</button><button onClick={()=>setConfirm({label:'Restart this project? Progress and thinking records will be cleared.',run:()=>onRestart(p)})}>{t('Restart')}</button><button onClick={()=>setConfirm({label:'Remove this local project?',run:()=>onRemove(p.id)})}>{t('Remove')}</button></div></article>)}</div>;
 return <main id="main" className="project-hub">
 {researchMode&&<div className="hub-actions research-hub"><strong>{t('Research / Teacher mode')}</strong><button onClick={()=>onView('Library')}>{t('My Task Library')}</button><button onClick={()=>onView('Create')}>{t('Create Task')}</button><span>{t('Choose a task to configure a controlled session.')}</span></div>}
 {view==='Home'&&<><section className="hub-hero"><span className="hub-tag">STEMPath AI</span><h1>{t('Choose a STEM project and begin your inquiry.')}</h1><p>{t('Explore real questions, collect evidence and grow your ideas with a thinking partner.')}</p><div className="hub-actions"><button className="primary-button" onClick={()=>onView('Challenges')}>{t('Choose a Project')}</button><button onClick={()=>onView('Create')}>{t('Create a Project')}</button></div></section><section><h2>{t('Recent Projects')}</h2>{projects.length?projectCards(projects.slice(0,3)):<p className="hub-empty">{t('You haven’t started a project yet.')} <button onClick={()=>onView('Challenges')}>{t('Choose a Project')}</button></p>}</section><section><h2>{t('Example Challenges')}</h2>{cards(examples.slice(0,3))}</section><section className="hub-how"><h2>{t('How STEMPath Works')}</h2><p>{t('Choose a task → Explore seven stages → Record evidence → Reflect on your learning')}</p></section></>}
 {(view==='Challenges'||view==='Library')&&<><h1>{t(view==='Library'?'My Task Library':'Challenges')}</h1><p>{t('Preview a task before starting your own project.')}</p><div className="hub-actions"><button className="primary-button" onClick={()=>onView('Create')}>{t('Create a Project')}</button><label>{t('Task type')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{t('All task types')}</option>{taskTypes.map(type=><option key={type} value={type}>{t(type)}</option>)}</select></label></div><h2>{t('My Task Library')}</h2>{library.length?cards(library,view==='Library'&&researchMode):<p>{t('Save a custom task here to reuse it in another lesson.')}</p>}{view==='Challenges'&&<><h2>{t('Example Challenges')}</h2>{cards(examples)}</>}{view==='Library'&&researchMode&&<section className="hub-card"><h2>{t('Import / Export')}</h2><label>{t('Task JSON')}<textarea rows={6} value={json} onChange={e=>setJSON(e.target.value)}/></label><div className="hub-actions"><button onClick={()=>{try{onImport(importTasks(json));setJSON('');setError('');}catch{setError(t('Invalid task JSON. Check the required title and description.'));}}}>{t('Import JSON')}</button><button onClick={()=>setExported(exportTasks(library))}>{t('Export Task Library')}</button></div>{error&&<p role="alert">{error}</p>}</section>}</>}
 {view==='My Projects'&&<><h1>{t('My Projects')}</h1><p>{t('Saved on this browser only. Continue where you left off.')}</p>{projects.length?projectCards(projects):<p>{t('You haven’t started a project yet.')}</p>}<button className="primary-button" onClick={()=>onView('Challenges')}>{t('Choose a Project')}</button></>}
 {view==='Resources'&&<><h1>{t('Resources')}</h1><div className="hub-grid">{['Ask a testable question','Make a fair comparison','Record evidence','Question AI suggestions'].map((key,i)=><article className="hub-card" key={key}><span className="hub-tag">0{i+1}</span><h2>{t(key)}</h2><p>{t(['Choose something you can observe or measure. What result could challenge your idea?','Change one factor and keep relevant conditions consistent. Repeat the test.','Record every result, units and conditions. Separate observations from explanations.','AI can make mistakes. Ask what evidence supports a claim and check it yourself.'][i])}</p></article>)}</div></>}
 {view==='Preview'&&preview&&<section className="hub-preview hub-card"><span className="hub-tag">{t(preview.type)}</span><h1>{shown(preview).title}</h1><p>{shown(preview).description}</p><div className="hub-grid">{(['context','objectives','constraints','successCriteria','availableMaterials','relevantDomains','subject','gradeLevel','lessonNumber','estimatedMinutes','safetyNotes'] as const).map(key=>{const v=shown(preview)[key];return v&&<section key={key}><h3>{t(key)}</h3>{Array.isArray(v)?<ul>{v.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p>{v}{key==='estimatedMinutes'?` ${t('minutes')}`:''}</p>}</section>})}</div><p>{t('Language availability')}: {[...new Set([/[\u3400-\u9fff]/.test(preview.title)?'zh-CN':'en',...Object.keys(preview.translations??{})])].map(l=>l==='zh-CN'?'中文':'English').join(' / ')}</p><div className="hub-actions"><button className="primary-button" onClick={()=>onStart(preview)}>{t('Start Project')}</button><button onClick={()=>onView('Challenges')}>{t('Back to Projects')}</button>{researchMode&&<button onClick={()=>onEdit(preview)}>{t('Edit')}</button>}</div></section>}
 {view==='Preview'&&preview&&researchMode&&<AITaskCheck key={preview.id+':'+(preview.taskRevision??1)} task={preview}/>}
 {view==='Create'&&<TaskEditor key={editing?.id??'new'} initial={editing} onSave={onSave} onPreview={onPreview} onStart={onStart}/>}
 {exported&&<section className="hub-card" role="region" aria-label={t('Export preview')}><h2>{t('Export JSON')}</h2><textarea aria-label={t('Export preview')} readOnly rows={10} value={exported}/><button onClick={()=>{const url=URL.createObjectURL(new Blob([exported],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stempath-tasks.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{t('Download JSON')}</button><button onClick={()=>setExported('')}>{t('Close')}</button></section>}
 {confirm&&<div className="hub-confirm" role="alertdialog" aria-modal="true" aria-label={t(confirm.label)}><div className="hub-card"><p>{t(confirm.label)}</p><button onClick={()=>setConfirm(null)}>{t('Cancel')}</button><button onClick={()=>{confirm.run();setConfirm(null);}}>{t('Confirm')}</button></div></div>}
 </main>;
}
function TaskEditor({initial,onSave,onPreview,onStart}:{initial:STEMTask|null;onSave:(t:STEMTask)=>void;onPreview:(t:STEMTask)=>void;onStart:(t:STEMTask)=>void}){
 const {t}=useI18n();const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{
 const value:Record<string,unknown>={...initial,id:initial?.id??crypto.randomUUID(),title:data.get('title'),description:data.get('description'),type:data.get('type')||undefined};
 for(const key of ['context','subject','gradeLevel','lessonNumber','teacherNotes','safetyNotes','additionalInstructions'])value[key]=String(data.get(key)||'')||undefined;
 for(const key of ['objectives','constraints','successCriteria','availableMaterials','relevantDomains','tags'])value[key]=String(data.get(key)||'').split('\n').map(s=>s.trim()).filter(Boolean);
 value.estimatedMinutes=data.get('estimatedMinutes')?Number(data.get('estimatedMinutes')):undefined;
 const enTitle=String(data.get('enTitle')||''),enDescription=String(data.get('enDescription')||'');
 value.translations=(enTitle||enDescription)?{...initial?.translations,en:{...initial?.translations?.en,...(enTitle?{title:enTitle}:{}),...(enDescription?{description:enDescription}:{})}}:initial?.translations;
 const task=reviseTask(loadTask(value),initial??undefined);const action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');
 if(action==='preview')onPreview(task);else if(action==='start')onStart(task);else{onSave(task);setSaved(true);}setError('');
 }catch{setError(t('Check the task fields and their length.'));}}
 return <section className="hub-card task-editor"><h1>{t(initial?'Edit Task':'Create STEM Project')}</h1><form onSubmit={submit} onChange={()=>setSaved(false)}><h2>{t('Basic information')}</h2><label>{t('Title')}<input name="title" required maxLength={160} defaultValue={initial?.title}/></label><label>{t('Description')}<textarea name="description" required maxLength={4000} defaultValue={initial?.description}/></label><h2>{t('Learning context')}</h2><div className="hub-grid">{(['subject','gradeLevel','lessonNumber','estimatedMinutes'] as const).map(k=><label key={k}>{t(k)}<input name={k} type={k==='estimatedMinutes'?'number':'text'} min={1} max={10000} maxLength={2000} defaultValue={initial?.[k]}/></label>)}</div><h2>{t('STEM task information')}</h2><label>{t('Task type')}<select name="type" defaultValue={initial?.type??''}><option value="">{t('Suggest from description')}</option>{taskTypes.map(type=><option key={type} value={type}>{t(type)}</option>)}</select></label>{(['context','objectives','constraints','successCriteria','availableMaterials','relevantDomains','tags','safetyNotes','teacherNotes','additionalInstructions'] as const).map(k=><label key={k}>{t(k)}{['objectives','constraints','successCriteria','availableMaterials','relevantDomains','tags'].includes(k)&&` · ${t('One item per line')}`}<textarea name={k} maxLength={k==='context'||k.includes('Notes')||k==='additionalInstructions'?2000:3600} defaultValue={Array.isArray(initial?.[k])?(initial![k] as string[]).join('\n'):initial?.[k]}/></label>)}<details><summary>{t('Optional English version')}</summary><label>{t('English title')}<input name="enTitle" maxLength={160} defaultValue={initial?.translations?.en?.title}/></label><label>{t('English description')}<textarea name="enDescription" maxLength={4000} defaultValue={initial?.translations?.en?.description}/></label><p>{t('Both language versions share the same task ID. Other translated fields can be imported as JSON.')}</p></details>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">{t('Saved to Task Library')}</p>}<div className="hub-actions"><button className="primary-button" name="action" value="save">{t('Save to Task Library')}</button><button name="action" value="preview">{t('Preview')}</button><button name="action" value="start">{t('Start Project')}</button></div></form></section>;
}
