'use client';
import { useState } from 'react';
import { conditions,conditionConfig,type Condition,type ResearchConfig } from '@/lib/research/config';
import type { ResearchController } from '@/lib/research/useResearchSession';
import type { ResearchSession } from '@/lib/research/session';
import type { Decision } from '@/lib/pedagogy/decisionEngine';
import { listSavedSessions,readSavedSession,type SavedSession } from '@/lib/research/storage';
import { downloadSession,exportJSON,exportCSV } from '@/lib/research/export';
import { assignTask, scenarioPresets } from '@/lib/research/assignment';
import { demoTasks } from '@/data/tasks';
import { taskTypes,loadTask } from '@/lib/stem/tasks';
import type { STEMTask,TaskType } from '@/types';
export function ResearchPanel({research,task,decision,onReset,onClear,onTask,onHide}:{research:ResearchController;task:STEMTask;decision:Decision;onReset:(config:ResearchConfig,task?:STEMTask)=>void;onClear:(all:boolean)=>void;onTask:(task:STEMTask)=>void;onHide:()=>void}){
 const [type,setType]=useState<TaskType|'all'>('all'),[seed,setSeed]=useState(research.session?.config.seed??''),[json,setJson]=useState(''),[error,setError]=useState(''),[confirm,setConfirm]=useState<'current'|'all'|null>(null);
 const [exported,setExported]=useState<{text:string;name:string}|null>(null),[copyStatus,setCopyStatus]=useState('');
 function exportSession(session:ResearchSession,format:'json'|'csv',now=Date.now()){setExported({text:format==='json'?exportJSON(session,now):exportCSV(session,now),name:`stempath-session-${session.sessionId}.${format}`});setCopyStatus('');downloadSession(session,format,now);}
 const [savedSessions,setSavedSessions]=useState<SavedSession[]>([]);
 const s=research.session,config=s?.config??conditionConfig();
 function randomTask(){try{const next=assignTask(demoTasks,type,seed);research.configure({...config,randomTaskMode:true,seed});onTask(next);setError('');}catch(err){setError((err as Error).message);}}
 return <details className="rail-section research-panel" open><summary>Research workspace · local only</summary><p>No names or participant identifiers. Settings here are not shown in student view. This panel is not access-controlled.</p>
 <dl><dt>Session ID</dt><dd>{s?.sessionId??'Recording paused — no current session'}</dd><dt>Current task / stage</dt><dd>{task.title} / {s?.currentStage??'understand'}</dd><dt>Condition / support</dt><dd>{config.condition} / Level {s?.supportLevel??1}</dd><dt>Events / saved sessions</dt><dd>{s?.events.length??0} / {research.savedCount}</dd></dl>
 {research.storageNotice&&<p role="alert">{research.storageNotice}</p>}
 <div className="research-actions"><button onClick={()=>s&&exportSession(s,'json')} disabled={!s}>Export JSON</button><button onClick={()=>s&&exportSession(s,'csv')} disabled={!s}>Export CSV</button><button onClick={onHide}>Enter student view</button><button onClick={()=>onReset({...config,storeMessageText:false})}>{s?'Start fresh session':'Start session'}</button></div>
 {exported&&<details open className="export-preview"><summary>Export preview · {exported.name}</summary><p>If your browser blocks downloads, copy the exact export below.</p><textarea aria-label="Export preview" readOnly value={exported.text} rows={8}/><button onClick={async()=>{try{await navigator.clipboard.writeText(exported.text);setCopyStatus('Copied export');}catch{setCopyStatus('Select the preview text and copy it manually.');}}}>Copy export</button><button onClick={()=>setExported(null)}>Close export preview</button><span role="status">{copyStatus}</span></details>}
 <label>Research condition<select aria-label="Research condition" value={config.condition} onChange={e=>onReset(conditionConfig(e.target.value as Condition))}>{conditions.map(c=><option key={c}>{c}</option>)}</select></label><small>Changing condition starts a clean session; the previous session remains saved locally.</small>
 <label><input type="checkbox" checked={config.storeMessageText} disabled={!s||!!s.completedAt} onChange={e=>{research.textStorage(e.target.checked);setExported(null);}}/> Store message and artifact text locally (default OFF)</label><p>OFF exports metadata only. ON also stores future messages and artifact revisions; do not enter personal information. Turning OFF removes captured text from this session, but cannot recall downloaded exports or other saved sessions.</p>
 <details><summary>Study settings</summary>{(['enableAIChallenge','enableFading','enableEscalation','allowManualSupportChange'] as const).map(key=><label key={key}><input type="checkbox" checked={config[key]} disabled={!s||!!s.completedAt} onChange={e=>research.configure({...config,[key]:e.target.checked})}/>{key}</label>)}<small>Low Support never proactively escalates or fades. No AI always blocks generation. CUSTOM starts conservatively and uses these settings.</small></details>
 <details><summary>Task assignment</summary><label>Demo task<select aria-label="Assign demo task" defaultValue="" onChange={e=>{const t=demoTasks.find(t=>t.id===e.target.value);if(t)onTask(t);}}><option value="" disabled>Select a task…</option>{demoTasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Eligible task type<select value={type} onChange={e=>setType(e.target.value as TaskType|'all')}><option value="all">All task types</option>{taskTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Optional random seed<input value={seed} maxLength={80} onChange={e=>setSeed(e.target.value)} placeholder="pilot01"/></label><button onClick={randomTask}>Assign random task</button><small>Same seed and same eligible task list select the same task. No participant randomization is performed.</small><label>Custom task JSON<textarea aria-label="Custom task JSON" value={json} maxLength={16000} onChange={e=>setJson(e.target.value)} placeholder={'{"title":"My question","description":"What will you investigate?"}'}/></label><button onClick={()=>{try{onTask(loadTask(JSON.parse(json)));setError('');}catch(err){setError((err as Error).message);}}}>Load JSON task</button><p>The existing “Load STEM Challenge” form also accepts manual tasks. Use ?task=plants for a demo task link; external JSON can use the existing injectTask interface.</p></details>
 <details><summary>Development scenarios</summary>{scenarioPresets.map(p=><button key={p.label} onClick={()=>onReset(conditionConfig(p.condition),demoTasks.find(t=>t.id===p.taskId)!)}>{p.label}</button>)}</details>
 <details><summary>Detected learner state</summary><pre>{JSON.stringify(decision,null,2)}</pre></details>
 <details><summary>Saved session exports</summary><button onClick={()=>{try{setSavedSessions(listSavedSessions(localStorage));}catch{setError('Saved sessions could not be read.');}}}>Refresh saved sessions</button>{savedSessions.map(item=><div key={item.sessionId}><small>{item.startedAt} · {item.condition} · {item.completed?'completed':'not completed'} · Text {item.textStored?'ON':'OFF'}<br/>{item.sessionId}</small>{(['json','csv'] as const).map(format=><button key={format} onClick={()=>{try{const saved=readSavedSession(localStorage,item.sessionId);exportSession(saved,format,Date.parse(saved.updatedAt??saved.startedAt));}catch(err){setError((err as Error).message);}}}>Export saved {format.toUpperCase()} {item.sessionId.slice(0,8)}</button>)}</div>)}</details>
 <details><summary>What is stored locally?</summary><p>Anonymous session metadata, task type and random task-run ID, events, support changes, approximate elapsed stage timing and artifact revision metadata. Text capture is {config.storeMessageText?'ON':'OFF'}. Existing learning notes and task drafts are separate browser records.</p><p>Reload starts a new session; earlier sessions remain in this browser. Export the current session before reload. Timing includes idle/background time and is not time-on-task measurement.</p><p>{s?.droppedEvents??0} early events omitted by the 5,000-event rolling limit.</p><button onClick={()=>setConfirm('current')}>Clear current session</button><button onClick={()=>setConfirm('all')}>Clear all local research data</button>{confirm&&<div role="alert"><p>{confirm==='all'?'Delete all saved research sessions and the legacy trace from this browser?':'Delete this session’s stored research data?'} Downloaded files and ordinary notebook notes are unaffected. Recording will pause.</p><button onClick={()=>{onClear(confirm==='all');setExported(null);setConfirm(null);}}>Confirm clear</button><button onClick={()=>setConfirm(null)}>Cancel</button></div>}</details>
 {error&&<p role="alert">{error}</p>}</details>;
}
