'use client';
import {useEffect,useState} from 'react';
import {useI18n} from '@/lib/i18n';
import {platformFetch} from '@/lib/persistence/client';
import {demoTasks} from '@/data/tasks';
import {loadTask} from '@/lib/stem/tasks';
import {conditionConfig,conditions} from '@/lib/research/config';
import type {Account} from '@/lib/server/accounts';
interface Credential {account:Account;displayPIN:string;}
function download(text:string,name:string,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ResearcherAccounts(){
 const {locale}=useI18n(),zh=locale==='zh-CN';const [accounts,setAccounts]=useState<Account[]>([]),[status,setStatus]=useState<Record<string,unknown>[]>([]),[credentials,setCredentials]=useState<Credential[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[taskId,setTaskId]=useState(demoTasks[0].id),[custom,setCustom]=useState(''),[condition,setCondition]=useState('ADAPTIVE_SUPPORT'),[capture,setCapture]=useState(false),[remove,setRemove]=useState<Account|null>(null),[confirmation,setConfirmation]=useState('');
 async function reload(){const [a,s]=await Promise.all([platformFetch<{accounts:Account[]}>('admin/accounts'),platformFetch<{projects:Record<string,unknown>[]}>('admin/status')]);setAccounts(a.accounts);setStatus(s.projects);}
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await reload();setNotice(zh?'操作已完成。':'Action completed.');}catch(e){setError(e instanceof Error?e.message:'Please retry');}finally{setBusy(false);}}
 return <section className="hub-card account-admin"><h1>{zh?'参与者管理':'Participant management'}</h1><p>{zh?'仅显示编号和项目进度。首次 PIN 只在生成或重置后显示，请立即安全分发。':'Codes and project status only. PINs appear only after creation or reset; distribute securely.'}</p>{error&&<p role="alert">{error} <button disabled={busy} onClick={()=>void run(reload)}>{zh?'重试加载':'Retry loading'}</button></p>}{notice&&<p role="status">{notice}</p>}<div className="hub-grid"><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void run(async()=>{const r=await platformFetch<Credential>('admin/accounts','POST',{participantCode:d.get('code')});setCredentials([r]);});}}><h2>{zh?'创建一个账号':'Create participant'}</h2><label>{zh?'研究编号':'Participant Code'}<input name="code" required maxLength={32}/></label><button disabled={busy}>{zh?'创建':'Create'}</button></form><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void run(async()=>{const r=await platformFetch<{created:Credential[]}>('admin/batch','POST',{prefix:d.get('prefix'),start:Number(d.get('start')),count:Number(d.get('count'))});setCredentials(r.created);});}}><h2>{zh?'批量生成':'Generate accounts'}</h2><label>{zh?'前缀':'Prefix'}<input name="prefix" defaultValue="P" required pattern="[A-Z]{1,8}"/></label><label>{zh?'起始编号':'Start'}<input name="start" type="number" defaultValue={1} min={1} required/></label><label>{zh?'数量':'Count'}<input name="count" type="number" defaultValue={30} min={1} max={100} required/></label><button disabled={busy}>{zh?'生成':'Generate'}</button></form></div>
 {credentials.length>0&&<section className="credential-output"><h2>{zh?'仅本次显示的学习 PIN':'One-time PIN display'}</h2><p>{zh?'此分发表包含登录凭据，请妥善保管，不要混入研究数据。':'This distribution sheet contains login credentials. Keep it separate from research exports.'}</p><table><thead><tr><th>Participant Code</th><th>PIN</th></tr></thead><tbody>{credentials.map(c=><tr key={c.account.id}><td>{c.account.participantCode}</td><td>{c.displayPIN}</td></tr>)}</tbody></table><button onClick={()=>download('participantCode,temporaryPIN\r\n'+credentials.map(c=>`${c.account.participantCode},${c.displayPIN}`).join('\r\n'),'participant-distribution.csv')}>{zh?'导出分发表':'Export distribution sheet'}</button><button onClick={()=>setCredentials([])}>{zh?'隐藏 PIN':'Hide PINs'}</button></section>}
 <h2>{zh?'账号':'Accounts'}</h2><button onClick={()=>download('participantCode\r\n'+accounts.filter(a=>a.role==='STUDENT').map(a=>a.participantCode).join('\r\n'),'participant-codes.csv')}>{zh?'导出编号列表':'Export codes only'}</button><div className="account-table"><table><thead><tr><th>Code</th><th>Role</th><th>Status</th><th>{zh?'操作':'Actions'}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.participantCode}</td><td>{a.role}</td><td>{a.status}</td><td>{a.role==='STUDENT'&&<><button disabled={busy} onClick={()=>void run(async()=>{const r=await platformFetch<{displayPIN:string}>('admin/accounts/'+a.id+'/reset','POST',{});setCredentials([{account:a,displayPIN:r.displayPIN}]);})}>{zh?'重置 PIN':'Reset PIN'}</button><button disabled={busy||a.status==='DISABLED'} onClick={()=>void run(async()=>{await platformFetch('admin/accounts/'+a.id+'/disable','POST',{});})}>{zh?'停用':'Disable'}</button><button disabled={busy} onClick={()=>{setRemove(a);setConfirmation('');}}>{zh?'删除全部数据':'Delete platform data'}</button><button disabled={busy} onClick={()=>void run(async()=>{const r=await platformFetch<{export:string}>('admin/accounts/'+a.id+'/research');download(r.export,'research-'+a.participantCode+'.json','application/json');})}>{zh?'研究导出':'Research export'}</button></>}</td></tr>)}</tbody></table></div>
 <h2>{zh?'分配任务':'Assign task'}</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{const task=custom.trim()?loadTask(JSON.parse(custom)):demoTasks.find(t=>t.id===taskId)!;await platformFetch('admin/accounts/'+selected+'/assign','POST',{task,config:{...conditionConfig(condition as typeof conditions[number]),storeMessageText:capture}});});}}><label>{zh?'参与者':'Participant'}<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{zh?'请选择':'Choose'}</option>{accounts.filter(a=>a.role==='STUDENT'&&a.status==='ACTIVE').map(a=><option key={a.id} value={a.id}>{a.participantCode}</option>)}</select></label><label>{zh?'任务':'Task'}<select value={taskId} onChange={e=>setTaskId(e.target.value)}>{demoTasks.map(t=><option key={t.id} value={t.id}>{t.title} · r{t.taskRevision??1}</option>)}</select></label><label>{zh?'可选：自定义任务 JSON（含修订号）':'Optional custom task JSON (with revision)'}<textarea value={custom} onChange={e=>setCustom(e.target.value)} rows={3}/></label><label>{zh?'研究条件':'Research condition'}<select value={condition} onChange={e=>setCondition(e.target.value)}>{conditions.map(c=><option key={c}>{c}</option>)}</select></label><label><input type="checkbox" checked={capture} onChange={e=>setCapture(e.target.checked)}/>{zh?'按研究方案允许导出会话文字（默认关闭）':'Allow research text capture under the study policy (default OFF)'}</label><button disabled={busy}>{zh?'分配':'Assign'}</button></form>
 <h2>{zh?'项目状态':'Project status'}</h2><div className="account-table"><table><thead><tr><th>Code</th><th>Task</th><th>Stage</th><th>Completed</th></tr></thead><tbody>{status.map((r,i)=><tr key={i}><td>{String(r.participant_code)}</td><td>{String(r.task_title??'—')}</td><td>{String(r.current_stage??'—')}</td><td>{String(r.completed??0)} / 7</td></tr>)}</tbody></table></div>
 {remove&&<div role="alertdialog" aria-modal="true" className="hub-confirm"><section className="hub-card"><p>{zh?'删除会移除该账号、项目、聊天、小结、会话和研究事件，无法撤销。':'Deletion removes this account, projects, messages, checkpoints, sessions and research events permanently.'}</p><label>{`DELETE ${remove.participantCode}`}<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button onClick={()=>setRemove(null)}>{zh?'取消':'Cancel'}</button><button disabled={busy||confirmation!==`DELETE ${remove.participantCode}`} onClick={()=>void run(async()=>{await platformFetch('admin/accounts/'+remove.id,'DELETE',{confirmation});setRemove(null);setCredentials(v=>v.filter(c=>c.account.id!==remove.id));})}>{zh?'确认删除':'Confirm deletion'}</button></section></div>}
 </section>;
}
